// discussion.mjs — Chapitre 6 du mémoire : DISCUSSION (rédaction d'exercice).
//
// Discute les résultats du chapitre 5 au regard du protocole corrigé : revue de
// littérature (§ 2.2), cadre conceptuel (§ 3), et données rwandaises.
//
// RÉFÉRENCES — aucune n'est inventée :
//   · {p:23}, {p:52-55}, {p:6,7}  références du protocole corrigé (1 à 71) ;
//   · {c:cle}  référence ajoutée pendant la rédaction (references.mjs),
//              numérotée à la suite du protocole et listée pour vérification.
// Effectifs et valeurs : {N}, {n:CODE}, {v:clé}, comme au chapitre 5.

export const TITRE_DISCUSSION = "6. DISCUSSION";

export const blocsDiscussion = [
  { p: "Ce chapitre confronte les résultats à la revue de littérature et au cadre conceptuel, puis en examine les forces et les limites." },

  { h2: "6.1. Rappel des principaux résultats" },
  { p: "Trois résultats dominent. Le dépistage est « coupé en deux » : la tension est mesurée en CPN, tandis que la glycémie relève du laboratoire ou de la consultation des maladies chroniques ; elle n'était réalisable pour une femme enceinte que dans {v:glycPossible} centres sur {v:nbCentres}, sur des signes d'appel et à ses frais. La part informative du dépistage, celle qui fonde la capacité de la femme à agir, est modulée à l'inverse des besoins ({n:C4} participants). Les conditions limitantes relèvent surtout du système — programme de rattachement, indicateurs, intrants, référence, rupture à l'accouchement —, mais une majorité de participants reconnaissent une part qui leur revient." },

  { h2: "6.2. Discussion des résultats" },
  { h3: "6.2.1. Deux programmes dans le même centre : la glycémie hors de la CPN" },
  { p: "Les recommandations internationales font de la CPN le lieu d'une mesure systématique de la pression artérielle et d'un dépistage du diabète orienté par les facteurs de risque {p:11}, et la Déclaration de Jakarta fait des milieux de vie le cadre privilégié de l'action promotionnelle {p:12}. Les participants partagent cette lecture ; pourtant, la moitié du dépistage n'appartient pas matériellement à la CPN. La décentralisation des soins chroniques s'est prolongée par le mentorat d'infirmiers de centres de santé, qui suivent désormais l'hypertension non sévère et le diabète de type 2 {c:niyonsenga}, dans la logique du paquet essentiel de l'OMS {p:14} : le glucomètre a suivi ce programme. Deux programmes coexistent ainsi sans articulation formelle, ce que la revue identifiait comme l'absence de dispositif portant la jonction entre santé maternelle et maladies chroniques {p:63,64}, et ce qui donne un contenu matériel au déficit de mise en œuvre pointé par l'Appel de Nairobi {p:22}." },
  { p: "Les données nationales concordent : le dépistage du diabète gestationnel n'est pas systématique au Rwanda, et la seule prévalence estimée en centre de santé public, 3,2 %, provient d'une épreuve réalisée pour la recherche {p:27} ; selon l'enquête STEPS de 2022, 87,0 % des femmes n'avaient jamais eu de mesure de la glycémie, contre 38 % pour la tension {p:16}. Là où le circuit est ouvert, la glycémie reste doublement sélective : sur des signes appréciés par chaque prestataire, faute de critères écrits, puis sur les moyens, le test ne figurant pas dans le paquet de soins de la CPN. Or la couverture de l'assurance communautaire, qui atteint 85,3 % {p:59}, n'empêche pas le recours de rester concentré parmi les plus aisés {p:61,62}. Cette seconde sélection porte sur ce que la Charte d'Ottawa demande de corriger en conférant à chacun les moyens de sa santé {p:23}. Elle invite aussi à ne pas lire la faible prévalence rwandaise, alors que les estimations africaines varient selon les critères {p:6,7,35-37}, comme une donnée épidémiologique pure : une partie de l'écart pourrait tenir au dépistage lui-même." },

  { h3: "6.2.2. Le prestataire, opérateur concret de l'équité" },
  { p: "La littérature établit un gradient social du recours et de la qualité du suivi prénatal au Rwanda {p:52-55} et des obstacles documentés du point de vue des femmes {p:56,57} ; un seul travail avait interrogé des prestataires {p:58}. Nos résultats décrivent un mécanisme par lequel le service lui-même reproduit l'inégalité : l'explication la plus complète va aux femmes qui en ont le moins besoin, ce qui rappelle la « loi inverse des soins » {c:tudorHart}, ici à l'échelle de quelques minutes, dans une même salle. Au regard de l'axe « acquérir des aptitudes individuelles » de la Charte {p:23}, une explication qui se raccourcit devant les femmes les moins instruites transforme une inégalité de littératie en santé {c:nutbeam} en inégalité de capacité d'agir {p:51}, comme l'expérience de la CPN en groupe montre que la portée capacitante d'un service ne se lit pas dans ses indicateurs de contact {p:65,66}." },
  { p: "Les participants ne décrivent pas un choix délibéré mais un rationnement sous contrainte de temps, propre aux agents de première ligne {c:lipsky}, dans un pays où la densité de professionnels qualifiés reste très inférieure au seuil de l'OMS {p:70}. Les contre-pratiques décrites — faire reformuler, montrer une image commune, ne pas classer les femmes par avance — rejoignent le principe d'universalisme proportionné {c:marmot}." },

  { h3: "6.2.3. Ce qui est compté existe, et ce qui est compté peut tromper" },
  { p: "Ce qui n'est pas compté au titre de la CPN n'y est ni commandé, ni réparé, ni supervisé. Le mentorat clinique conduit dans des districts voisins, qui a porté l'évaluation complète des signes de danger de 2,1 % à 84,2 % des consultations {p:68}, montre que ces pratiques dépendent de conditions modifiables. À l'inverse, un contrôle portant sur la complétude produit de la complétude : plus un indicateur sert à la décision, plus il déforme les pratiques qu'il devait mesurer {c:campbell}, ce que rejoint la faible concordance entre indicateurs prénatals et registres rwandais {p:69}. Ce résultat, qui repose surtout sur un entretien, ne permet aucune estimation de fréquence ; il indique qu'un indicateur utile doit porter sur l'acte et sa suite, et être vérifié par l'observation." },

  { h3: "6.2.4. Du signalement à la prise en charge" },
  { p: "La revue inventoriait des facteurs limitants récurrents en Afrique de l'Est et centrale {p:24-26} sans montrer leur articulation ; le thème « trouver sans pouvoir suivre » l'apporte : la détection n'a de valeur que si le transport, la décision du ménage et le retour d'information tiennent. L'absence de retour, rapportée par {n:F3} participants, rejoint les pratiques sous-optimales de référence décrites dans 121 centres de santé rwandais {c:rurangirwa}. Ces résultats relèvent de l'axe « créer des milieux favorables » et de la stratégie « servir de médiateur » de la Charte {p:23}, et soulignent une discontinuité peu traitée : la sortie du suivi à l'accouchement, alors que la grossesse peut révéler ces affections pour la première fois {p:4,5}. Les relais communautaires, que le programme national mobilise déjà pour les maladies non transmissibles {p:63,64}, réduisent une partie de cet écart, mais déplacent l'inégalité entre les villages qui disposent d'un agent actif et les autres." },

  { h3: "6.2.5. Une portée reconnue en équité, sans le mot" },
  { p: "Sans que le mot soit prononcé, {n:H2} participants sur {N} jugent inacceptables les différences décrites, et les situent dans les conditions — l'heure, le lieu, le matériel — plutôt que dans les femmes, ce qui correspond à la définition de l'équité retenue {p:51} et à la place que la Charte lui donne parmi les conditions préalables à la santé {p:23}. Que {n:H5} participants reconnaissent une part qui leur revient indique que la réorientation des services trouve chez eux un point d'appui ; la résignation d'une minorité rappelle que le jugement d'équité dépend aussi de ce qui paraît possible." },

  { h2: "6.3. Retour sur le cadre conceptuel" },
  { p: "Sur les {v:nbCodes} codes de l'arbre final, {v:nbInductifs} sont nés du matériau. Ils ne remettent pas en cause l'articulation des deux ensembles du cadre, mais suggèrent trois révisions (tableau VIII), dont la plus directe : le modèle socio-écologique retenu {p:41} ne permet pas de voir qu'un intrant présent dans le centre peut rester inaccessible au service, ou à la femme, qui en a besoin." },
  { tableau: "cadre" },

  { h2: "6.4. Forces et limites de l'étude" },
  { p: "Forces. L'échantillon couvre quinze des seize centres du district et chacune des modalités du tableau II ; la puissance informationnelle {p:44} a été appréciée dimension par dimension plutôt que par un critère de saturation discuté {p:45}. La triangulation a mis en évidence des concordances autant que des écarts, et l'observation a situé le glucomètre. La fidélité du codage a été contrôlée par un double codage de {v:relusInter} entretiens (κ = {v:kappaInter}) et un recodage intra-codeur de {v:relusIntra} entretiens (κ = {v:kappaIntra}) ; les interprétations ont été soumises à trois participants. Ces procédures répondent aux critères de rigueur retenus {p:46}, et le rapportage suit la grille COREQ {p:47}." },
  { p: "Limites. Les résultats portent sur des pratiques déclarées et sur des représentations professionnelles ; le point de vue des femmes reste hors champ, et une désirabilité sociale est possible. L'observation d'une demi-journée est exposée à un effet de la présence de l'observateur {c:mccambridge}, et les données de routine sont de qualité limitée {p:69}. La traduction depuis le kinyarwanda comporte un risque de perte de sens, contrôlé par une vérification indépendante. Portant sur un seul district, l'étude ne se généralise pas, mais la description du contexte permet d'apprécier sa transférabilité." },
  { p: "Perspectives. Trois prolongements paraissent prioritaires : recueillir le point de vue des femmes sur l'explication reçue ; mesurer la couverture effective de la glycémie chez les femmes enceintes à partir des registres des laboratoires ; suivre les femmes dépistées après l'accouchement. Les suggestions qui découlent de l'étude sont présentées en conclusion." },
];

// Tableau VIII — révisions du cadre (mémo « Piste d'audit 3 » du projet).
export const revisionsCadre = [
  ["Niveau organisationnel", "Distinguer l'intrant présent, l'intrant utilisable, l'intrant accessible à la CPN et le test accessible sans frais à la femme", "Glucomètre au laboratoire ou à la consultation des maladies chroniques ; bandelettes réservées, absentes ou périmées ; appareils en panne ; test hors du paquet de la CPN, payé par la femme (thèmes 1 et 5)"],
  ["Entre le service et le social perçu", "Ajouter une articulation communautaire", "Relais des agents de santé communautaire, suivi des femmes référées (thème 7)"],
  ["Niveau systémique", "Faire du dispositif de contrôle une condition à part entière", "Indicateurs et complétude des registres orientent l'attention et peuvent masquer l'inégalité (thèmes 4 et 6)"],
];

// Recommandations par destinataire : tableau du chapitre 6 dans le document séparé et du rapport ;
// dans le mémoire, elles sont reprises sous forme de suggestions en conclusion.
export const recommandations = [
  ["Ministère de la Santé et Rwanda Biomedical Centre", "Inscrire la glycémie de la femme enceinte dans le paquet de soins de la CPN, sans frais pour elle ; fixer par écrit les signes d'appel et les facteurs de risque qui justifient le test", "Thème 1"],
  ["Direction de la santé du district", "Rattacher explicitement la glycémie de la femme enceinte à la CPN : réserver au laboratoire une part des bandelettes pour les bons de la CPN, et inclure ces bandelettes et les piles des tensiomètres dans les intrants essentiels ; inscrire dans le rapport mensuel une ligne sur le dépistage (tensions mesurées, glycémies réalisées, résultats anormaux, références abouties) ; organiser la maintenance des appareils ; superviser par l'observation des actes et non par la seule complétude des registres", "Thèmes 1, 4, 5 et 6"],
  ["Responsables des centres de santé", "Organiser le circuit « bon de CPN → laboratoire » le matin même ; coordonner la CPN et la consultation des maladies chroniques pour l'usage du glucomètre", "Thème 1"],
  ["Hôpital de district", "Rendre systématique le retour d'information vers le centre pour chaque femme référée ; organiser le suivi après l'accouchement des femmes dépistées", "Thème 3"],
  ["Équipes de CPN", "Vérifier la compréhension en faisant reformuler la femme ; utiliser un support visuel commun ; consacrer davantage de temps d'explication aux femmes qui en ont le plus besoin ; tracer les références", "Thème 2"],
  ["Formation initiale et continue", "Former les infirmiers affectés aux constantes autant que les sages-femmes ; former des équipes plutôt que des personnes ; intégrer la pratique informative et sa distribution entre les femmes au contenu des formations", "Thèmes 1 et 2 ; conditions individuelles"],
  ["Programme de santé communautaire", "Appuyer le rôle des agents dans le suivi des femmes référées et après l'accouchement, et reconnaître les outils de suivi créés localement", "Thème 7"],
];
