// discussion.mjs — Chapitre 6 du mémoire : DISCUSSION (version d'entraînement).
//
// Discute les résultats du chapitre 5 au regard du protocole corrigé : revue de
// littérature (§ 2.2), cadre conceptuel (§ 3), et données rwandaises.
//
// RÉFÉRENCES — aucune n'est inventée :
//   · {p:23}, {p:52-55}, {p:6,7}  références du protocole corrigé (1 à 71) ;
//   · {c:cle}  référence ajoutée pendant la rédaction (references.mjs),
//              numérotée à la suite du protocole et listée pour vérification.
// Effectifs et valeurs : {N}, {n:CODE}, {v:clé}, comme au chapitre 5.

export const TITRE_DISCUSSION = "6. DISCUSSION";

export const blocsDiscussion = [
  { h2: "6.1. Rappel des principaux résultats" },
  { p: "Le dépistage est « coupé en deux » : la tension est mesurée à chaque visite ; la glycémie, prévue pour toutes à la première CPN, relève du laboratoire, n'était effectivement réalisée que dans {v:glycPossible} centres sur {v:nbCentres} et n'est refaite nulle part de façon systématique à 24-28 semaines. L'explication est modulée à l'inverse des besoins ({n:C4} participants). Les limites relèvent surtout du système, mais une majorité de participants reconnaissent une part qui leur revient." },

  { h2: "6.2. Discussion des résultats" },
  { h3: "6.2.1. Deux programmes dans le même centre" },
  { p: "Les recommandations font de la CPN le lieu d'une mesure systématique de la pression artérielle et d'un dépistage du diabète orienté par les facteurs de risque {p:11}, et des milieux de vie le cadre de l'action promotionnelle {p:12}. Or la décentralisation des soins chroniques, prolongée par le mentorat d'infirmiers de centres de santé {c:niyonsenga} dans la logique du paquet essentiel de l'OMS {p:14}, a rattaché le glucomètre à la consultation des maladies chroniques. Deux programmes coexistent sans la jonction que la revue jugeait absente {p:63,64}, ce qui donne un contenu matériel au déficit de mise en œuvre pointé par l'Appel de Nairobi {p:22}. Les données nationales concordent : dépistage du diabète gestationnel non systématique, prévalence de 3,2 % estimée pour la recherche {p:27}, et 87,0 % des femmes jamais testées pour la glycémie contre 38 % pour la tension {p:16}. En CPN, au contraire, la tension a été mesurée chez 93,5 % des femmes suivies dans la province de l'Est selon l'EDS 2025 {c:eds2025} : l'écart entre les deux dépistages tient à l'organisation plus qu'à la règle." },
  { p: "La règle elle-même n'est pas en cause : le diabète fait partie des affections recherchées chez toutes les femmes à la première CPN et consignées au registre de maternité {c:schmidt}, et cette visite doit avoir lieu avant 12 semaines dans le modèle national à huit contacts, qui prévoit aussi un contact à 26 semaines {c:rbcAnc}. Deux limites tiennent à l'organisation. La première est matérielle : là où le laboratoire manque de bandelettes ou les réserve aux malades chroniques, même le test de la première CPN n'est pas fait, et la case du registre peut rester vide ou être remplie sans test (thème 6). La seconde tient au calendrier : un test unique, au premier trimestre, repère un diabète préexistant mais pas le diabète gestationnel, qui apparaît surtout entre 24 et 28 semaines, période pour laquelle le protocole national prévoit une épreuve de charge {p:27} que les participants ne pratiquent pas, alors que le contact de 26 semaines s'y prêterait. Cette lacune invite à ne pas lire la faible prévalence rwandaise, quand les estimations africaines varient selon les critères et le moment du test {p:6,7,35-37}, comme une donnée épidémiologique pure : à Kigali, une cohorte testée entre 24 et 28 semaines selon les critères de 2013 trouvait 19,5 %, dans une population il est vrai très favorisée {c:nshimiyumuremyi}." },

  { h3: "6.2.2. Le prestataire, opérateur concret de l'équité" },
  { p: "La littérature établit un gradient social du suivi prénatal {p:52-55} et des obstacles vus par les femmes {p:56,57}, mais un seul travail avait interrogé des prestataires {p:58}. Ce gradient s'est resserré pour le contact : de l'EDS 2019-2020 à l'EDS 2025, la part des femmes ayant eu au moins quatre visites est passée de 47,2 % à 77,5 %, et l'écart entre les quintiles extrêmes de 21,5 à 7,6 points {p:10}{c:eds2025}. L'inégalité se déplace donc vers le contenu de la consultation. Nos résultats décrivent comment le service reproduit l'inégalité : l'explication va d'abord aux femmes qui en ont le moins besoin, à l'image de la « loi inverse des soins » {c:tudorHart}. Au regard de l'axe « aptitudes individuelles » de la Charte {p:23}, une inégalité de littératie {c:nutbeam} devient une inégalité de capacité d'agir {p:51} ; la CPN en groupe montre d'ailleurs que cette portée ne se lit pas dans les indicateurs de contact {p:65,66}. Il s'agit d'un rationnement sous contrainte de temps {c:lipsky}, dans un pays en déficit de professionnels {p:70}, où un quart des prestataires de CPN de 121 centres déclaraient consacrer 15 minutes ou moins à une femme {c:rurangirwa} ; les contre-pratiques décrites rejoignent l'universalisme proportionné {c:marmot}. La séance d'éducation collective en offre le contre-modèle : un universalisme sans proportion, le même message pour les présentes et rien pour celles qui arrivent après elle. Elle n'en est pas moins un levier : la CPN de groupe expérimentée au Rwanda a accru les connaissances et le soutien entre pairs {p:66}, alors que la connaissance des signes de danger reste partielle chez les femmes suivies {c:uwiringiyimana}. Y inscrire la tension et le sucre, et ne jamais en faire un substitut de la restitution individuelle, relève de l'axe « aptitudes individuelles » de la Charte {p:23}." },

  { h3: "6.2.3. Ce qui est compté, et ce qui le suit" },
  { p: "Ce qui n'est pas compté au titre de la CPN n'y est ni commandé, ni réparé, ni supervisé ; le mentorat clinique a montré que ces pratiques changent quand on leur porte attention {p:68}. À l'inverse, contrôler la complétude produit de la complétude {c:campbell}, comme le suggère la faible concordance entre indicateurs prénatals et registres rwandais {p:69}. Le financement basé sur la performance donne à ce mécanisme sa forme rwandaise : il rémunère les centres pour des volumes de services, dont la première CPN précoce et les quatre visites {c:schmidt}, et son évaluation a montré un effet plus net sur les services les mieux payés et les moins exigeants pour le prestataire {c:basinga}. La détection, enfin, n'a de valeur que si la référence aboutit : les facteurs limitants inventoriés ailleurs {p:24-26} s'articulent ici en une chaîne — transport, décision du ménage, retour d'information —, dont les animatrices de santé maternelle, chargées dans chaque village de repérer les femmes enceintes et de les orienter vers la CPN {c:condo}, assurent parfois le dernier maillon (thème 7), en accord avec les pratiques de référence sous-optimales décrites au Rwanda, où moins de la moitié des prestataires citaient la prééclampsie parmi les motifs de référence urgente {c:rurangirwa}, alors que 82 % des décès maternels d'un hôpital de référence concernaient des femmes référées, dont 15 % par troubles hypertensifs {c:rulisa}, et le suivi s'interrompt à l'accouchement alors que la grossesse peut révéler ces affections {p:4,5}. Les dispositifs nationaux jouent dans les deux sens : la venue du conjoint attendue à la première CPN retarde des femmes, comme l'avaient décrit Påfs et al. {p:57} ; les aides ciblées de l'ubudehe — mutuelle prise en charge {p:61,62} et farine Shisha Kibondo {c:shisha} — rapprochent les plus pauvres du service, au risque d'un effet de seuil ; l'alerte téléphonique des ASM a fait progresser les accouchements en établissement {c:ngabo} mais reste un outil d'urgence ; et les campagnes de dépistage des maladies non transmissibles, qui révèlent beaucoup d'hypertensions ignorées {c:campagneMnt}, ne sont pas reliées à la CPN. À l'inverse, l'umugoroba w'ababyeyi, forum villageois des parents déjà mobilisé pour l'éducation nutritionnelle {c:nsanzabera}, offrirait un relais vers les maris et les familles, que la séance du centre n'atteint pas. Ces résultats relèvent des milieux favorables et de la médiation {p:23}." },

  { h3: "6.2.4. Une portée reconnue en équité" },
  { p: "Sans que le mot soit prononcé, {n:H2} participants sur {N} jugent inacceptables des différences qu'ils situent dans les conditions plutôt que dans les femmes, conformément à la définition de l'équité retenue {p:51} ; que {n:H5} reconnaissent une part qui leur revient donne un point d'appui à la réorientation des services." },

  { h2: "6.3. Retour sur le cadre conceptuel" },
  { p: "Sur les {v:nbCodes} codes de l'arbre final, {v:nbInductifs} sont nés du matériau. Ils ne remettent pas en cause les deux ensembles du cadre, mais appellent trois révisions (tableau VIII), que la figure 3 intègre : une cascade d'accès à la glycémie au niveau organisationnel, que le modèle socio-écologique {p:41} ne laissait pas voir ; le dispositif de contrôle comme condition systémique ; une articulation communautaire ; et trois dimensions de l'équité d'accès — au test, à l'explication, à la continuité." },
  { figure: "cadre_conceptuel_revise.png", legende: "Figure 3. Cadre conceptuel révisé à la lumière des résultats", source: "auteur, à partir de la figure 1, du tableau VIII et des observations" },
  { tableau: "cadre" },

  { h2: "6.4. Forces et limites de l'étude" },
  { p: "Forces. L'échantillon couvre quinze des seize centres et chaque modalité du tableau II ; la puissance informationnelle {p:44} a été appréciée par dimension plutôt que par saturation {p:45} ; la fidélité du codage a été contrôlée (κ = {v:kappaInter} ; intra-codeur κ = {v:kappaIntra}) ; la rigueur répond aux critères retenus {p:46} et à la grille COREQ {p:47}." },
  { p: "Limites. Les résultats portent sur des pratiques déclarées et des représentations professionnelles ; le point de vue des femmes reste hors champ. Les entretiens n'ayant pas été enregistrés, les extraits sont des propos notés : leur formulation exacte n'est pas garantie, ce que la vérification des interprétations auprès des participants atténue. L'observation est exposée à un effet de présence {c:mccambridge}, les données de routine sont de qualité limitée {p:69}, et l'étude, limitée à un district, ne se généralise pas. Les perspectives et suggestions sont présentées en conclusion." },
];

// Tableau VIII — révisions du cadre (mémo « Piste d'audit 3 » du projet).
export const revisionsCadre = [
  ["Niveau organisationnel", "Distinguer l'intrant présent, l'intrant utilisable, l'intrant accessible à la CPN et le moment du test au cours de la grossesse", "Glucomètre au laboratoire ou à la consultation des maladies chroniques ; bandelettes réservées, absentes ou périmées ; glycémie unique à la première CPN, non refaite à 24-28 semaines (thèmes 1 et 5)"],
  ["Pratique informative", "Distinguer l'information collective (séance d'éducation) et la restitution individuelle du résultat", "Séance égale pour les présentes, muette sur le résultat ; manquée par les femmes arrivées tard (thème 2)"],
  ["Entre le service et le social perçu", "Ajouter une articulation communautaire", "Relais des ASM et de leur alerte téléphonique, forums villageois (umugoroba w'ababyeyi), suivi des femmes référées (thème 7)"],
  ["Niveau systémique", "Faire du dispositif de contrôle une condition à part entière", "Indicateurs et complétude des registres orientent l'attention et peuvent masquer l'inégalité (thèmes 4 et 6)"],
];

// Recommandations par destinataire : tableau du chapitre 6 dans le document séparé et du rapport ;
// dans le mémoire, elles sont reprises sous forme de suggestions en conclusion.
export const recommandations = [
  ["Ministère de la Santé et Rwanda Biomedical Centre", "Relier les campagnes de dépistage des MNT à la CPN (signalement au centre des femmes enceintes dépistées) ; garantir les bandelettes nécessaires à la glycémie de la première CPN ; préciser et rendre praticable le dépistage du diabète gestationnel entre 24 et 28 semaines (glycémie à jeun ou épreuve de charge du protocole national, au contact de 26 semaines du modèle à huit contacts), avec des critères écrits pour les femmes à risque", "Thème 1"],
  ["Direction de la santé du district", "Rattacher explicitement la glycémie de la femme enceinte à la CPN : réserver au laboratoire une part des bandelettes pour les bons de la CPN, et inclure ces bandelettes et les piles des tensiomètres dans les intrants essentiels ; inscrire dans le rapport mensuel une ligne sur le dépistage (tensions mesurées, glycémies réalisées, résultats anormaux, références abouties) ; organiser la maintenance des appareils ; superviser par l'observation des actes et non par la seule complétude des registres", "Thèmes 1, 4, 5 et 6"],
  ["Responsables des centres de santé", "Organiser le circuit « bon de CPN → laboratoire » le matin même, pour la première CPN et pour le contrôle à 24-28 semaines ; coordonner la CPN et la consultation des maladies chroniques pour l'usage du glucomètre", "Thème 1"],
  ["Hôpital de district", "Rendre systématique le retour d'information vers le centre pour chaque femme référée ; organiser le suivi après l'accouchement des femmes dépistées", "Thème 3"],
  ["Équipes de CPN", "Inscrire la tension et le sucre au programme des séances d'éducation, avec une image simple ; reprendre le message pour les femmes arrivées après la séance ; ne jamais substituer la séance à la restitution du résultat ; vérifier la compréhension en faisant reformuler la femme ; tracer les références", "Thème 2"],
  ["Formation initiale et continue", "Former les infirmiers affectés aux constantes autant que les sages-femmes ; former des équipes plutôt que des personnes ; intégrer la pratique informative et sa distribution entre les femmes au contenu des formations", "Thèmes 1 et 2 ; conditions individuelles"],
  ["Programme de santé communautaire", "Donner aux ASM et à l'umugoroba w'ababyeyi des messages simples sur la tension et le sucre pendant la grossesse ; prévoir dans l'outil de signalement des ASM le suivi d'une femme référée pour tension élevée ; faire savoir que la femme est reçue à la première CPN même sans son conjoint", "Thèmes 3 et 7"],
];
