// discussion.mjs — Chapitre 6 du mémoire : DISCUSSION (version d'entraînement).
//
// Discute les résultats du chapitre 5 au regard du protocole corrigé : revue de
// littérature (§ 2.2), cadre conceptuel (§ 3), et données rwandaises.
//
// RÉFÉRENCES — aucune n'est inventée :
//   · {p:23}, {p:52-55}, {p:6,7}  références du protocole corrigé (1 à 71) ;
//   · {c:cle}  référence ajoutée pendant la rédaction (references.mjs),
//              numérotée à la suite du protocole et listée pour vérification.
// Effectifs et valeurs : {N}, {n:CODE}, {v:clé}, comme au chapitre 5.

export const TITRE_DISCUSSION = "6. DISCUSSION";

export const blocsDiscussion = [
  { h2: "6.1. Rappel des principaux résultats" },
  { p: "La tension est mesurée à chaque visite et la glycémie est demandée pour toutes au premier contact et faite au laboratoire ; mais ce test saute les jours de rupture de bandelettes, de panne ou d'absence du laborantin — le jour de l'observation, il n'était fait que dans {v:glycFaite} centres sur {v:nbCentres} —, la femme manquée n'est presque jamais rattrapée, et il n'est refait nulle part de façon systématique à 24-28 semaines. L'explication est modulée à l'inverse des besoins ({n:C4} participants) et, après le diagnostic, l’autosurveillance à domicile reste réservée aux ménages aisés ({n:G15} participants). Les limites relèvent surtout du système, mais une majorité de participants reconnaissent une part qui leur revient." },

  { h2: "6.2. Discussion des résultats" },
  { h3: "6.2.1. Une règle pour toutes, une exécution intermittente" },
  { p: "Les recommandations font de la CPN le lieu d'une mesure systématique de la pression artérielle et d'un dépistage du diabète orienté par les facteurs de risque {p:11}, et des milieux de vie le cadre de l'action promotionnelle {p:12}. Dans les centres étudiés, la pratique va au-delà d'un dépistage ciblé : la CPN demande la glycémie capillaire pour toutes au premier contact, et le laboratoire la réalise ; la CPN ne la fait elle-même qu'en urgence, quand elle dispose d'un glucomètre. Ce qui la limite n'est donc ni la règle ni la technique, mais la continuité des intrants, de la maintenance et de la présence du laborantin. La décentralisation des soins chroniques, prolongée par le mentorat d'infirmiers de centres de santé {c:niyonsenga} dans la logique du paquet essentiel de l'OMS {p:14}, fait de la consultation des maladies chroniques un second utilisateur des bandelettes du centre : deux programmes puisent au même stock sans la jonction que la revue jugeait absente {p:63,64}, dans des pays où les bandelettes manquent souvent jusque dans les formations sanitaires {c:klatman}, ce qui donne un contenu matériel au déficit de mise en œuvre pointé par l'Appel de Nairobi {p:22}. Les données nationales rappellent l'enjeu : dépistage du diabète gestationnel non systématique, prévalence de 3,2 % estimée pour la recherche {p:27}, et 87,0 % des femmes jamais testées pour la glycémie contre 38 % pour la tension {p:16}. En CPN, la tension a été mesurée chez 93,5 % des femmes suivies dans la province de l'Est selon l'EDS 2025 {c:eds2025} : un test universel mais intermittent laisse passer des femmes que rien ne rattrape." },
  { p: "La règle de terrain trouve un appui dans le registre de maternité, où le diabète figure parmi les affections recherchées chez toutes les femmes à la première CPN {c:schmidt}, alors que les directives nationales de 2021 décrivent un dépistage du diabète gestationnel par bandelette urinaire, orienté par les facteurs de risque, dans un modèle à huit contacts où la première visite doit avoir lieu avant 12 semaines et où un contact est prévu à 26 semaines {c:rbcAnc}. Deux limites tiennent à l'organisation. La première est la continuité : une rupture de bandelettes, une panne ou l'absence d'un laborantin souvent seul suffit à interrompre le test, sans relais en CPN là où elle n'a ni glucomètre ni personne formée, et, faute de liste des femmes manquées, l'interruption devient une absence définitive pour celles qui se sont présentées ces jours-là ; la case du registre peut alors rester vide ou être remplie sans test (thème 6). La seconde tient au calendrier : un test unique, au premier trimestre, repère un diabète préexistant mais pas le diabète gestationnel, qui apparaît surtout entre 24 et 28 semaines, période pour laquelle le protocole national prévoit une épreuve de charge {p:27} que les participants ne pratiquent pas, alors que le contact de 26 semaines s'y prêterait. Cette lacune invite à ne pas lire la faible prévalence rwandaise, quand les estimations africaines varient selon les critères et le moment du test {p:6,7,35-37}, comme une donnée épidémiologique pure : à Kigali, une cohorte testée entre 24 et 28 semaines selon les critères de 2013 trouvait 19,5 %, dans une population il est vrai très favorisée {c:nshimiyumuremyi}." },

  { h3: "6.2.2. Le prestataire, opérateur concret de l'équité" },
  { p: "La littérature établit un gradient social du suivi prénatal {p:52-55} et des obstacles vus par les femmes {p:56,57}, mais un seul travail avait interrogé des prestataires {p:58}. Ce gradient s'est resserré pour le contact : de l'EDS 2019-2020 à l'EDS 2025, la part des femmes ayant eu au moins quatre visites est passée de 47,2 % à 77,5 %, et l'écart entre les quintiles extrêmes de 21,5 à 7,6 points {p:10}{c:eds2025}. L'inégalité se déplace donc vers le contenu de la consultation. Nos résultats décrivent comment le service reproduit l'inégalité : l'explication va d'abord aux femmes qui en ont le moins besoin, à l'image de la « loi inverse des soins » {c:tudorHart}. Au regard de l'axe « aptitudes individuelles » de la Charte {p:23}, une inégalité de littératie {c:nutbeam} devient une inégalité de capacité d'agir {p:51} ; la CPN en groupe montre d'ailleurs que cette portée ne se lit pas dans les indicateurs de contact {p:65,66}. Il s'agit d'un rationnement sous contrainte de temps {c:lipsky}, dans un pays en déficit de professionnels {p:70}, où un quart des prestataires de CPN de 121 centres déclaraient consacrer 15 minutes ou moins à une femme {c:rurangirwa} ; les contre-pratiques décrites rejoignent l'universalisme proportionné {c:marmot}. Le gradient réapparaît après le diagnostic : l'autosurveillance à domicile, avec un tensiomètre ou un glucomètre acheté par le ménage, n'est accessible qu'aux femmes aisées, souvent les plus proches du centre. Les femmes atteintes de prééclampsie se disent prêtes à mesurer leur tension chez elles, mais le coût de l'appareil arrête celles de faible niveau socio-économique {c:munyungula}, et les glucomètres et leurs bandelettes restent chers et peu accessibles dans les pays à ressources limitées {c:klatman} ; le même principe invite à rapprocher le suivi de celles qui ne peuvent pas se mesurer chez elles. La séance d'éducation collective en offre le contre-modèle : un universalisme sans proportion, le même message pour les présentes et rien pour celles qui arrivent après elle. Elle n'en est pas moins un levier : la CPN de groupe expérimentée au Rwanda a accru les connaissances et le soutien entre pairs {p:66}, alors que la connaissance des signes de danger reste partielle chez les femmes suivies {c:uwiringiyimana}. Y inscrire la tension et le sucre, et ne jamais en faire un substitut de la restitution individuelle, relève de l'axe « aptitudes individuelles » de la Charte {p:23}." },

  { h3: "6.2.3. Ce qui est compté, et ce qui le suit" },
  { p: "Ce qui n'est pas compté au titre de la CPN n'y est ni commandé, ni réparé, ni supervisé ; le mentorat clinique a montré que ces pratiques changent quand on leur porte attention {p:68}. À l'inverse, contrôler la complétude produit de la complétude {c:campbell}, comme le suggère la faible concordance entre indicateurs prénatals et registres rwandais {p:69}. Le financement basé sur la performance rémunère des volumes de services, dont la première CPN précoce et les quatre visites {c:schmidt}, avec un effet plus net sur les services les mieux payés et les moins exigeants {c:basinga}. La détection n'a de valeur que si la référence aboutit : les facteurs limitants inventoriés ailleurs {p:24-26} forment ici une chaîne — transport, décision du ménage, retour d'information — dont les ASM, chargées de repérer les femmes enceintes et de les orienter {c:condo}, assurent parfois le dernier maillon ; au Rwanda, moins de la moitié des prestataires citaient la prééclampsie parmi les motifs de référence urgente {c:rurangirwa}, et 82 % des décès maternels d'un hôpital de référence concernaient des femmes référées {c:rulisa}, alors que le suivi s'interrompt à l'accouchement {p:4,5}. Les dispositifs nationaux jouent dans les deux sens : la venue attendue du conjoint retarde des femmes {p:57} ; les aides de l'ubudehe {p:61,62}{c:shisha} rapprochent les plus pauvres, au risque d'un effet de seuil ; l'alerte téléphonique des ASM a fait progresser les accouchements en établissement {c:ngabo} mais reste un outil d'urgence ; les campagnes de dépistage des MNT {c:campagneMnt} ne sont pas reliées à la CPN ; l'umugoroba w'ababyeyi {c:nsanzabera} offrirait un relais vers les maris et les familles. Ces résultats relèvent des milieux favorables et de la médiation {p:23}." },

  { h3: "6.2.4. Une portée reconnue en équité" },
  { p: "Sans que le mot soit prononcé, {n:H2} participants sur {N} jugent inacceptables des différences qu'ils situent dans les conditions plutôt que dans les femmes, conformément à la définition de l'équité retenue {p:51} ; que {n:H5} reconnaissent une part qui leur revient donne un point d'appui à la réorientation des services." },

  { h2: "6.3. Retour sur le cadre conceptuel" },
  { p: "Sur les {v:nbCodes} codes de l'arbre final, {v:nbInductifs} sont nés du matériau. Ils ne remettent pas en cause les deux ensembles du cadre, mais appellent quatre révisions (tableau VII), que la figure 3 intègre : une cascade d'accès à la glycémie au niveau organisationnel, que le modèle socio-écologique {p:41} ne laissait pas voir ; dans la pratique informative, la distinction entre la séance d'éducation collective et la restitution individuelle du résultat ; une articulation communautaire ; le dispositif de contrôle comme condition systémique. La figure décompose en outre l'équité d'accès en trois dimensions : au test, à l'explication, à la continuité." },
  { figure: "cadre_conceptuel_revise.png", legende: "Figure 3. Cadre conceptuel révisé à la lumière des résultats", source: "auteur, à partir de la figure 1, du tableau VII et des observations" },
  { tableau: "cadre" },

  { h2: "6.4. Forces et limites de l'étude" },
  { p: "Forces. L'échantillon couvre quinze des seize centres et chaque modalité du tableau II ; la puissance informationnelle {p:44} a été appréciée par dimension plutôt que par saturation {p:45} ; la fidélité du codage a été contrôlée (§ 4.2.6) ; la rigueur répond aux critères retenus {p:46} et à la grille COREQ {p:47}." },
  { p: "Limites. Les résultats portent sur des pratiques déclarées et des représentations professionnelles ; le point de vue des femmes reste hors champ. Les entretiens n'ayant pas été enregistrés, les extraits sont des propos notés, dont la formulation exacte n'est pas garantie. L'observation est exposée à un effet de présence {c:mccambridge}, les données de routine sont de qualité limitée {p:69}, l'étude, limitée à un district, ne se généralise pas, et le kappa {c:landis}, calculé par paragraphe, est favorisé par les paragraphes qu'aucun codeur ne code : il atteste la cohérence de la grille, non la justesse de l'interprétation." },
];

// Tableau VII — révisions du cadre (mémo « Piste d'audit 3 » du projet).
export const revisionsCadre = [
  ["Niveau organisationnel", "Distinguer la règle (un test pour toutes), le test fait le jour même au laboratoire, le relais en CPN, le rattrapage du test manqué et le moment du test au cours de la grossesse", "Bandelettes en rupture ou périmées, glucomètre en panne, laborantin absent, aucun prélèvement après midi ; glucomètre d'urgence en CPN dans certains centres seulement ; femme manquée non rappelée ; glycémie non refaite à 24-28 semaines (thèmes 1 et 5)"],
  ["Pratique informative", "Distinguer l'information collective (séance d'éducation) et la restitution individuelle du résultat", "Séance égale pour les présentes, muette sur le résultat ; manquée par les femmes arrivées tard (thème 2)"],
  ["Entre le service et le social perçu", "Ajouter une articulation communautaire", "Relais des ASM et de leur alerte téléphonique, forums villageois (umugoroba w'ababyeyi), suivi des femmes référées (thème 7)"],
  ["Niveau systémique", "Faire du dispositif de contrôle une condition à part entière", "Indicateurs et complétude des registres orientent l'attention et peuvent masquer l'inégalité (thèmes 4 et 6)"],
];

// Recommandations par destinataire : tableau du chapitre 6 dans le document séparé et du rapport ;
// dans le mémoire, elles sont reprises sous forme de suggestions en conclusion.
export const recommandations = [
  ["Ministère de la Santé et Rwanda Biomedical Centre", "Relier les campagnes de dépistage des MNT à la CPN ; garantir sans rupture les bandelettes de la glycémie de la première CPN ; rendre praticable le dépistage du diabète gestationnel entre 24 et 28 semaines (glycémie à jeun ou épreuve de charge, au contact de 26 semaines), avec des critères écrits pour les femmes à risque", "Thème 1"],
  ["Direction de la santé du district", "Inclure les bandelettes de la CPN et les piles des tensiomètres dans les intrants essentiels, avec un seuil d'alerte ; doter chaque CPN d'un glucomètre d'urgence et former à son usage tous ses prestataires ; garantir la présence d'un laborantin ou d'un remplaçant aux heures de CPN ; ajouter au rapport mensuel une ligne sur le dépistage et sa suite ; organiser la maintenance ; superviser les actes, pas seulement la complétude des registres", "Thèmes 1, 4, 5 et 6"],
  ["Responsables des centres de santé", "Tenir la liste des femmes dont le test n'a pas pu être fait et le refaire au rendez-vous suivant ; organiser le passage au laboratoire le matin même, avant la fermeture ; organiser le contrôle à 24-28 semaines ; prévoir un suivi plus rapproché des femmes dépistées qui ne peuvent pas se surveiller à domicile", "Thèmes 1 et 3"],
  ["Hôpital de district", "Rendre systématique le retour d'information vers le centre pour chaque femme référée ; organiser le suivi après l'accouchement des femmes dépistées", "Thème 3"],
  ["Équipes de CPN", "Inscrire la tension et le sucre au programme des séances d'éducation, avec une image simple ; reprendre le message pour les femmes arrivées après la séance ; ne jamais substituer la séance à la restitution du résultat ; vérifier la compréhension en faisant reformuler la femme ; tracer les références", "Thème 2"],
  ["Formation initiale et continue", "Former les infirmiers affectés aux constantes autant que les sages-femmes ; former des équipes plutôt que des personnes ; intégrer la pratique informative et sa distribution entre les femmes au contenu des formations", "Thèmes 1 et 2 ; conditions individuelles"],
  ["Programme de santé communautaire", "Donner aux ASM et à l'umugoroba w'ababyeyi des messages simples sur la tension et le sucre pendant la grossesse ; prévoir dans l'outil de signalement des ASM le suivi d'une femme référée pour tension élevée ; faire savoir que la femme est reçue à la première CPN même sans son conjoint", "Thèmes 3 et 7"],
];
