// DONNÉES SIMULÉES — P01 et P02 (CS03, urbain, volume élevé)
// Convention : ["E", …] = enquêteur ; ["P", …] = participant.
// Les entretiens conduits en kinyarwanda sont rendus en français par le
// chercheur ; les termes propres au discours du participant sont conservés
// en kinyarwanda entre crochets, suivis de leur rendu français (§ 4.2.6).

export const P01 = {
  journal: "Entretien conduit dans le bureau du titulaire, porte fermée, en fin de matinée après la consultation. Deux interruptions brèves (un agent venu faire signer un document, un appel téléphonique auquel le participant n'a pas répondu). Participant à l'aise, débit posé, emploie spontanément le vocabulaire des directives. Attitude d'exposé plus que de confidence sur les premières questions ; se déplace vers un registre plus personnel à partir de Q10. Enregistrement de bonne qualité. Remarque du chercheur : ma position d'étudiant en santé publique a pu installer un registre de présentation du service ; j'ai insisté sur les récits de cas pour en sortir.",
  reponses: {
    O1: [["P", "J'ai fait l'école d'infirmier, la filière A1, et j'ai commencé au service curatif dans un centre plus au sud. Après quelques années on m'a nommé ici, et comme titulaire on fait un peu tout — mais la consultation prénatale, je l'ai prise parce que la sage-femme était seule et qu'il fallait deux personnes le matin. Alors voilà, depuis plus de dix ans je suis dans les deux, curatif et prénatal. Et maintenant, comme titulaire, je supervise aussi."]],
    O2: [["P", "La journée commence tôt. Les femmes arrivent avant nous, parfois à six heures. On ouvre, on fait l'appel des carnets, et on répartit : une personne aux constantes, une personne à la consultation, et selon le jour une troisième qui fait la vaccination. Le matin est chargé, l'après-midi c'est plus calme, on fait les écritures, les rapports. Le mardi et le vendredi ce sont les jours les plus chargés, on peut monter à quarante-cinq, cinquante femmes."]],
    Q1: [["P", "Bon. La femme arrive, elle donne son carnet. On l'inscrit dans le registre. Ensuite elle passe aux constantes : le poids, la taille si c'est la première fois, la tension [umuvuduko w'amaraso]. Après ça elle attend, et elle entre pour la consultation : on demande l'âge de la grossesse, on regarde s'il y a des signes de danger, on palpe l'abdomen, on écoute le cœur du bébé. On donne le fer, l'acide folique, on fait le test du paludisme si nécessaire, la sérologie si elle n'a pas encore. Et on fixe le rendez-vous suivant."], ["E", "Et ensuite ?"], ["P", "Ensuite elle repart. Si quelque chose n'est pas normal, on la garde, on reprend, ou on l'envoie à l'hôpital."]],
    Q2: [["P", "La tension, c'est aux constantes, au tout début. C'est systématique, ça fait partie des constantes comme le poids. Le sucre… (silence) le sucre c'est différent. On a un glucomètre, mais les bandelettes, on en a douze en ce moment. Douze. Alors on ne peut pas faire à tout le monde. On le fait quand il y a quelque chose qui nous inquiète : une femme corpulente, une femme qui a déjà eu un gros bébé, une femme dont la mère est diabétique, ou si la bandelette urinaire montre du sucre. Sinon non."], ["E", "Vous avez employé le mot « inquiète », qu'entendez-vous par là ?"], ["P", "Qu'il y a un signe qui me fait penser au diabète. Ce n'est pas écrit dans un protocole ici, c'est ce qu'on a appris à la formation de 2023, les facteurs de risque. Donc je choisis."]],
    Q3: [["P", "Oui. Il y a deux mois, une femme de trente-quatre ans, troisième grossesse, à peu près sept mois. Aux constantes on trouve 168 sur 104. L'agent m'appelle. Je la fais asseoir, je la laisse se reposer vingt minutes, je reprends moi-même : 160 sur 100. Je fais la bandelette urinaire, il y avait des protéines, deux croix. Là j'ai su que c'était sérieux."], ["E", "Comment cela s'est-il passé exactement ?"], ["P", "J'ai rempli la fiche de référence, j'ai expliqué à la femme, et son mari était dehors — je l'ai fait entrer parce qu'il fallait qu'ils partent le jour même à Kibungo. Ils sont partis l'après-midi. Elle est revenue deux semaines après avec le traitement, elle avait été hospitalisée trois jours. Celle-là, ça s'est bien passé. Parce que le mari était là et qu'ils avaient de quoi payer le transport."]],
    Q4: [["P", "Je lui ai dit que la pression de son sang était trop élevée, que ce n'était pas bon ni pour elle ni pour l'enfant, que ça pouvait provoquer des convulsions [kugagara] et qu'il fallait aller à l'hôpital aujourd'hui, pas demain. J'ai expliqué qu'il y avait des protéines dans ses urines et que les deux ensemble, c'est le signe d'une maladie de la grossesse qu'on appelle la prééclampsie. Je lui ai dit de ne pas attendre d'avoir mal à la tête ou de mal voir pour y aller."]],
    Q5: [["P", "(silence) Ça dépend beaucoup. Celle-là, je pense qu'elle a compris, parce qu'elle a posé des questions et qu'elle est partie le jour même. Mais en général… en général je crois qu'elles comprennent qu'il y a un danger et qu'il faut aller à l'hôpital. Le mot « tension », elles le connaissent. Ce qu'elles ne comprennent pas, c'est que ça peut continuer après l'accouchement. Ça, non."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Qu'une tension élevée pendant la grossesse, ce n'est pas seulement un problème de grossesse. Qu'après, il faut continuer à se faire contrôler. Parce qu'elles accouchent, tout va bien, et on ne les revoit plus jamais. Et dix ans après elles reviennent avec une hypertension installée."]],
    Q6: [["P", "Oui, forcément. Avec une femme qui a fait l'école, je peux aller plus loin, je peux parler du sel, du poids, du contrôle après l'accouchement. Avec quelqu'un qui n'a pas été à l'école, je réduis : je dis l'essentiel, « votre pression est élevée, il faut aller à l'hôpital ». Je ne vais pas lui expliquer la prééclampsie."], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "L'expérience. Si je donne trop d'informations, elle retient la peur et pas le message. Alors je simplifie. Mais… (silence) c'est vrai que celle qui aurait le plus besoin d'explications, c'est peut-être celle-là. Je n'y avais pas pensé comme ça."]],
    Q7: [["P", "La tension, c'est devenu une routine, ça ne me demande rien. Le sucre, c'est autre chose : c'est une charge en plus, et une charge dont je n'ai pas les moyens. Si je compare avec le reste — le fer, la sérologie, le paludisme, le suivi du bébé — le dépistage de ces deux maladies vient après. Pas parce que c'est moins important, mais parce que le reste est demandé, et ça, personne ne le demande vraiment."]],
    Q8: [["P", "Oui, ça en fait partie. La femme enceinte vient chez nous quatre fois, cinq fois ; c'est souvent la seule fois dans sa vie d'adulte où elle voit un soignant régulièrement. Si on ne mesure pas sa tension là, on la mesure où ? Donc oui, c'est notre rôle. Mais notre rôle a grandi sans que les moyens grandissent avec."]],
    Q9: [["P", "Ce qui m'aide, c'est d'avoir une salle de constantes séparée. Ça peut paraître petit mais ça change tout : la personne aux constantes ne fait que ça, elle ne saute pas la tension parce qu'elle est appelée ailleurs. Et puis nous sommes quatre le matin. Et j'ai eu la formation de 2023, donc je sais ce que je cherche. Ah, et l'affiche avec les seuils, au mur : les agents n'ont pas besoin de me demander à partir de quand ils m'appellent."]],
    Q10: [["P", "En juin et juillet on n'a eu aucune bandelette de glycémie pendant six semaines. Six semaines. Pendant ce temps-là, une femme corpulente avec des antécédents, je ne pouvais rien faire, je l'envoyais à l'hôpital pour une glycémie — et beaucoup n'y allaient pas, parce que c'est un déplacement, c'est un jour de travail perdu. Donc concrètement, pendant six semaines, le dépistage du diabète n'existait pas ici."], ["E", "Comment l'expliquez-vous ?"], ["P", "L'approvisionnement. On commande, ça vient en petite quantité, ou ça ne vient pas. Je ne sais pas si c'est le district ou plus haut. Nous, on remplit les commandes."]],
    Q11: [["P", "Oui, il y a des différences. Il y a celles qui viennent tôt, dès qu'elles savent, celles-là on les suit bien, on a le temps de tout faire. Il y a celles qui arrivent à sept, huit mois : avec elles on court, on fait l'essentiel. Et il y a les jours de grande affluence où, je vais être franc, on va plus vite avec tout le monde."], ["E", "Pouvez-vous m'en dire davantage ?"], ["P", "Les femmes du centre-ville connaissent le service, elles demandent. Une femme qui vient de loin, qui arrive fatiguée, qui ne parle pas beaucoup, elle prend ce qu'on lui donne. Elle ne demande pas sa tension. Et si l'agent est débordé, c'est celle-là qui passe sans."]],
    Q12: [["P", "Celles qui viennent de loin et qui ont peu de moyens. Parce que même si je trouve quelque chose, je sais que la suite va être difficile : le transport à Kibungo, la mutuelle qu'elles n'ont pas toujours payée, le mari qui doit accepter. Alors quand je vois la fiche, je sais déjà que ça va coincer plus loin."]],
    Q13: [["P", "Je reprends la tension après repos. Si c'est confirmé, je remplis la fiche de référence, je garde la souche, et je l'envoie à l'hôpital de district. Mon rôle s'arrête là. Officiellement je devrais savoir ce qu'elle est devenue, mais il n'y a pas de retour : l'hôpital ne nous écrit pas. Je l'apprends si elle revient, ou par la sage-femme si elle la croise au marché."], ["E", "Et quand cela ne se passe pas comme prévu ?"], ["P", "Elle ne va pas. Elle revient au rendez-vous suivant avec la fiche encore dans son carnet. Ça arrive. Et là je recommence l'explication, autrement."]],
    Q14: [["P", "Plusieurs raisons. D'abord, beaucoup ne savent pas qu'il faut venir tôt : elles pensent qu'on vient à la CPN quand le ventre se voit. Ensuite il y a celles qui cachent la grossesse au début, pour des raisons qui leur appartiennent. Et puis il y a la distance et les travaux des champs : en saison de récolte, elles ne viennent pas. Elles reviennent après."]],
    Q15: [["P", "En 2023 j'ai eu une formation de trois jours sur les maladies non transmissibles, à Kibungo, avec le paquet — le PEN de l'OMS. C'est là que j'ai appris les facteurs de risque du diabète gestationnel. Avant ça, rien. Dans ma formation d'infirmier, on nous a parlé de l'hypertension de l'adulte, pas de la femme enceinte, et pas du tout du diabète de grossesse. Et mes collègues qui n'ont pas eu cette formation, ils n'ont que ce que je leur transmets."]],
    Q16: [["P", "(silence) Honnêtement ? Ils regardent autre chose. Quand la supervision vient, on vérifie le nombre de premières consultations, le nombre de quatrièmes consultations, la vaccination, le planning familial. La tension, on ne me l'a jamais demandée comme indicateur. Le diabète, jamais. Donc ce n'est pas qu'ils s'y opposent — ça n'est pas dans leur regard."]],
    Q17: [["P", "Les bandelettes. Un approvisionnement régulier en bandelettes de glycémie, et un glucomètre de réserve. Pourquoi celle-là ? Parce que pour la tension, nous savons faire et nous avons l'appareil : ce qui manque, c'est la moitié du dépistage. Aujourd'hui je fais la moitié du travail et j'appelle ça un dépistage."]],
    Q18: [["P", "Qu'ils décident si ce dépistage est demandé ou non. S'il est demandé, qu'il entre dans les indicateurs et que les intrants suivent. S'il n'est pas demandé, qu'on nous le dise, et nous arrêterons de faire semblant. Ce qui est difficile, c'est l'entre-deux : on nous dit que c'est important et rien ne vient."]],
    Q19: [["P", "(silence) Non. Ce n'est pas normal. Deux femmes entrent le même matin dans la même salle, et l'une a un dépistage complet et l'autre non — ce n'est pas normal. Mais je vais vous dire : ce n'est pas nous. Moi je ne choisis pas les bandelettes que je reçois."], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "Parce que quand j'ai les moyens, je le fais pour tout le monde, sans distinction. Quand je n'en ai pas, je dois choisir, et choisir c'est déjà injuste. Ce n'est pas moi qui ai créé ce choix."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "De l'approvisionnement, d'abord. Et de la charge du jour. Et un peu de nous, je l'admets : un jour où on est fatigués, on explique moins bien."]],
    Q20: [["P", "Une chose. On parle de dépister, mais on ne parle jamais de ce qui vient après. Une femme que j'ai dépistée hypertendue, après son accouchement, personne ne la suit. Elle n'est plus enceinte, donc elle ne relève plus de la CPN ; et la consultation des maladies chroniques, elle ne sait pas qu'elle existe. On la trouve, et on la perd. Ça, ça me dérange plus que les bandelettes."]],
  },
};

export const P02 = {
  journal: "Entretien en français, à la demande de la participante, dans la salle de réunion du centre. Aucune interruption. Débit rapide, phrases longues, revient d'elle-même sur ses réponses pour les nuancer. Se montre ouvertement critique, y compris envers sa propre pratique, ce qui est rare dans les premiers entretiens : la position de non-titulaire y contribue peut-être. À deux reprises, demande si l'enregistrement peut être coupé — je l'ai coupé à sa demande lors d'un passage relatif à un collègue, non transcrit et non analysé. Réflexion du chercheur : j'ai relancé trop vite sur Q6, en suggérant presque la réponse ; à surveiller.",
  reponses: {
    O1: [["P", "J'ai fait la formation de sage-femme A1, à Kigali. J'ai travaillé deux ans en maternité, dans un hôpital, et puis je suis venue ici pour des raisons familiales. Ici, c'est un centre de santé, donc on fait la CPN, l'accouchement, le planning. Depuis cinq ans environ, et la CPN c'est mon poste principal, plus de deux ans à temps plein."]],
    O2: [["P", "C'est intense le matin et calme l'après-midi. On reçoit entre trente-cinq et cinquante femmes selon les jours. Nous sommes deux ou trois à la consultation, plus un agent aux constantes. La journée type, c'est : les constantes, la consultation, les examens, les médicaments, le rendez-vous. Répété quarante fois. Et entre les deux, les accouchements qui arrivent, parce qu'on est aussi la maternité — donc la CPN s'arrête, on court, et on revient."]],
    Q1: [["P", "Alors. Elle arrive, elle s'inscrit, elle passe à la salle des constantes : poids, tension, et à la première visite la taille. Ensuite elle attend son tour. En consultation, j'ouvre le carnet, je regarde le terme, je demande comment elle se sent, les signes de danger — maux de tête, vue trouble, œdèmes, saignements, mouvements du bébé. J'examine : hauteur utérine, bruits du cœur fœtal, présentation si c'est avancé. Je prescris le fer et l'acide folique, le déparasitage au bon terme, la moustiquaire à la première visite. Je vérifie les vaccins, la sérologie, le test du paludisme si elle a de la fièvre. Et je fixe le rendez-vous. Voilà le cadre."]],
    Q2: [["P", "La tension est dans les constantes, donc au début et de façon systématique — chez nous vraiment systématique, parce qu'il y a une salle pour ça et une personne pour ça. Le sucre, non. On a le glucomètre, mais les bandelettes sont comptées. Nous en avons douze ce mois. Donc la recherche du sucre, elle n'est pas dans le déroulement : elle est en dehors, elle dépend de moi, de mon jugement, de ce que je trouve à la bandelette urinaire. Et ça, c'est un problème, parce que ce qui dépend du jugement de chacune n'est pas égal d'une femme à l'autre."]],
    Q3: [["P", "J'ai un cas qui me reste. Une jeune femme, première grossesse, vingt-deux ans peut-être, à peu près trente semaines. Tension à 150 sur 95, reprise après repos, toujours 148 sur 92. Pas de protéines. Pas de symptômes. Une hypertension de grossesse, sans prééclampsie. Et elle ne comprenait pas pourquoi je m'inquiétais, puisqu'elle ne se sentait pas malade."], ["E", "Que s'est-il passé ?"], ["P", "Je lui ai expliqué, je l'ai fait revenir à une semaine, j'ai noté dans son carnet de revenir avant si maux de tête. Elle est revenue. La tension avait un peu baissé, et on a continué à la suivre de près jusqu'à l'accouchement, qui s'est bien passé. Mais pendant trois semaines, chaque fois qu'elle venait, je devais recommencer l'explication, parce que « elle ne se sentait pas malade ». C'est ça qui est difficile : une maladie qui ne fait pas mal."]],
    Q4: [["P", "Je lui ai dit que la tension, c'est la force avec laquelle le sang pousse dans les vaisseaux, et que quand elle pousse trop fort pendant la grossesse, le placenta reçoit moins bien, et le bébé peut moins bien grandir. Que ça peut aussi devenir dangereux pour elle, brutalement. J'ai utilisé l'image d'un tuyau — je ne sais pas si c'est très juste médicalement, mais ça fonctionne. Et je lui ai dit les signes pour lesquels elle doit venir tout de suite sans attendre le rendez-vous."]],
    Q5: [["P", "Ce qu'elle comprend et ce que je dis, ce sont deux choses différentes. Je crois qu'elles comprennent surtout l'émotion : est-ce que la soignante est inquiète ou pas. Si je suis calme, elles pensent que ce n'est rien. Si je suis pressante, elles ont peur. Le contenu — le placenta, le risque — je pense que ça passe mal. Ce qui passe, c'est « il faut aller à l'hôpital » ou « il faut revenir »."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Qu'elle a le droit de demander sa tension. Que ce n'est pas un service qu'on lui rend. Si elles savaient qu'elles peuvent demander, elles ne passeraient pas sans."]],
    Q6: [["P", "Oui, et je vais être honnête avec vous parce que c'est le cœur du problème. J'adapte selon le niveau d'instruction, selon la langue, selon le temps que j'ai. Avec une femme qui a fait le secondaire, je parle du long terme, de l'après-accouchement, du contrôle. Avec une femme qui n'a pas été à l'école, je descends au minimum : « ta tension est élevée, tu vas à l'hôpital ». Et c'est exactement à l'envers de ce qu'il faudrait."], ["E", "Pouvez-vous m'en dire davantage ?"], ["P", "Celle qui a fait le secondaire, elle ira chercher l'information ailleurs, elle a un téléphone, elle connaît quelqu'un. Celle à qui je dis deux mots, c'est tout ce qu'elle aura. Donc je donne le plus à celle qui a déjà, et le moins à celle qui n'a rien. Je le sais et je continue de le faire, parce que le temps me manque et parce que c'est plus facile. Ça, personne ne nous le dit en formation."]],
    Q7: [["P", "Pour la tension, c'est intégré, je ne le pense même plus. Pour le sucre, c'est devenu quelque chose que je n'ai plus l'habitude de faire, et ça, c'est dangereux : ce qu'on ne fait pas, on cesse d'y penser. Par rapport au reste — le fer, le paludisme, le VIH, la position du bébé — je dirais que ces deux maladies sont en bas de ma liste mentale. Pas par choix. Par habitude installée par le manque."]],
    Q8: [["P", "Oui, absolument. Et pas seulement pour la grossesse. La CPN, c'est le seul moment où une femme de vingt-cinq ou trente ans voit un soignant plusieurs fois de suite. C'est une porte d'entrée. Si on ne s'en sert pas, on attend qu'elle ait quarante-cinq ans et qu'elle arrive avec des complications. Donc oui, c'est notre rôle — et je dirais même que c'est un des rares endroits où ce rôle est possible."]],
    Q9: [["P", "La salle de constantes séparée, avec quelqu'un dedans. Le fait que nous soyons plusieurs. L'affiche avec les seuils, qui évite les discussions. Et la formation de 2024, qui m'a donné les mots pour expliquer — avant, je disais « ta tension est élevée » et je m'arrêtais là, parce que je ne savais pas quoi dire de plus."]],
    Q10: [["P", "Pendant la rupture de bandelettes, il y a eu une femme : trente-huit ans, quatrième grossesse, très corpulente, un enfant précédent de plus de quatre kilos. Le cas typique. Je n'avais rien. Je l'ai envoyée faire une glycémie à l'hôpital. Elle est revenue au rendez-vous suivant sans l'avoir faite — pas d'argent pour le déplacement ce jour-là, et elle avait un autre problème plus urgent. Donc je n'ai jamais su. Elle a accouché, tout s'est bien passé, mais je n'ai jamais su."], ["E", "Comment l'expliquez-vous ?"], ["P", "Par la rupture de stock, et par le fait qu'envoyer quelqu'un ailleurs, c'est perdre la personne. Chaque fois qu'on ajoute un déplacement, on perd une partie des femmes. C'est mécanique."]],
    Q11: [["P", "Oui. Il y a la différence de moment : celles qui viennent tôt et celles qui arrivent à sept mois. Il y a la différence de compréhension, et la différence de… comment dire… d'assurance. Certaines femmes occupent l'espace, posent des questions, demandent. D'autres attendent qu'on leur dise. Avec les premières, le dépistage est complet, parce qu'elles le réclament presque. Avec les secondes, il dépend entièrement de nous — et nous, on est fatigués à onze heures."]],
    Q12: [["P", "Celles qui viennent des collines les plus éloignées, celles qui n'ont pas payé la mutuelle, et celles qui viennent accompagnées de leur belle-mère plutôt que seules — parce qu'alors ce n'est pas elle qui décide de revenir. Je sais d'avance que si je trouve quelque chose, ça va se perdre en route. Et je crois — c'est désagréable à dire — que ça influence l'énergie que je mets à chercher."]],
    Q13: [["P", "Je reprends la tension après vingt minutes de repos, c'est la règle. Je fais la bandelette urinaire. Si c'est confirmé, deux cas : soit c'est sévère ou avec des protéines, et je réfère tout de suite à Kibungo avec la fiche ; soit c'est modéré, et je la garde en suivi rapproché, je la revois à une semaine. Mon rôle va jusque-là. Après, si elle est référée, je n'ai pas de nouvelles sauf si elle revient."], ["E", "Et quand cela ne se passe pas comme prévu ?"], ["P", "Elle ne part pas, ou elle part et on ne la revoit plus. Ou elle part, on la traite à l'hôpital, elle revient avec des comprimés dont je ne connais pas la posologie exacte parce qu'il n'y a pas de compte rendu. Alors je devine. Ce n'est pas normal mais je devine."]],
    Q14: [["P", "Pour les premières visites tardives : il y a l'idée qu'on vient quand la grossesse se voit ; il y a celles qui attendent d'être sûres ; et il y a celles qui ont eu quatre enfants et qui pensent connaître. Pour les non-retours : le coût du déplacement, la saison des travaux, et le fait que la CPN prend une demi-journée entière. Une femme qui vend au marché perd sa journée. Quand on ajoute un deuxième déplacement à l'hôpital, on lui demande deux journées. Elle choisit."]],
    Q15: [["P", "Le centre, en tant que tel, ne m'a pas préparée. C'est le district qui a organisé la formation de 2024, trois jours, et j'y suis allée. Ici, il y a la transmission entre nous : le titulaire nous a expliqué les facteurs de risque après sa formation. C'est informel. Dans ma formation initiale de sage-femme, l'hypertension de la grossesse oui, bien traitée ; le diabète gestationnel, presque rien, une heure de cours. Et rien sur comment l'expliquer à quelqu'un."]],
    Q16: [["P", "Ils regardent les chiffres qu'ils doivent remonter. Le nombre de CPN1, le taux de quatrième visite, les accouchements assistés. Je n'ai jamais vu personne demander combien de tensions élevées nous avons trouvées. Alors ce dépistage existe dans les discours et pas dans les tableaux. Et ce qui n'est pas dans les tableaux n'existe pas vraiment dans un système de santé."]],
    Q17: [["P", "Des supports d'information en kinyarwanda, avec des images, que je puisse donner à la femme ou lui montrer. Une seule feuille. Pourquoi celle-là plutôt que les bandelettes ? Parce que les bandelettes règlent le dépistage du sucre, mais ne règlent rien de ce que je viens de vous dire sur l'explication. Si j'ai une image à montrer, je donne la même chose à celle qui a fait l'école et à celle qui ne l'a pas faite. Ça corrige mon propre biais. Les bandelettes ne le corrigent pas."]],
    Q18: [["P", "Trois choses : que l'indicateur existe, que les intrants suivent, et qu'on nous donne du matériel éducatif conçu pour des gens qui ne lisent pas bien. La troisième, personne ne la demande jamais, et c'est celle qui touche à l'équité."]],
    Q19: [["P", "Non. Non, ce n'est pas normal, et le plus gênant c'est que la part qui dépend de moi n'est pas la plus petite. Je peux dire que c'est l'approvisionnement, et ce serait vrai. Mais quand je choisis d'expliquer longuement à l'une et deux mots à l'autre, ce n'est pas l'approvisionnement : c'est moi."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "Du stock, du nombre de femmes ce matin-là, de mon état de fatigue, et de la femme elle-même — de si elle demande ou pas. Quatre choses, dont une seule ne dépend pas du tout de nous."]],
    Q20: [["P", "Oui. Vous ne m'avez pas demandé ce que ça fait de savoir qu'on fait mal quelque chose et de continuer. On en parle entre nous parfois, et on se dit qu'on n'a pas le choix. Mais ce n'est pas tout à fait vrai : dans certaines choses, on a une petite marge, et on ne la prend pas. Je pense que vous devriez poser cette question aux autres aussi."]],
  },
};
