// DONNÉES SIMULÉES — P20 (CS15, infirmier âgé, équipement vétuste), P21 (CS16,
// centre le plus éloigné, titulaire, cahier de suivi après l'accouchement).
// Les termes en kinyarwanda entre crochets sont ILLUSTRATIFS.

export const P20 = {
  journal: "Entretien en kinyarwanda, dans la salle de consultation. Participant âgé, à l'approche de la retraite, ton tranquille, parfois fataliste. Montre spontanément le tensiomètre réparé au ruban adhésif. Évoque le recours aux guérisseurs sur un mode descriptif, sans jugement marqué. Aucune interruption. Réflexion : le registre de la résignation est ici plus net que dans aucun autre entretien ; je l'ai laissé se déployer sans le relancer vers la plainte ni vers l'espoir.",
  reponses: {
    O1: [["P", "Infirmier A2. Plus de trente ans de service, dans beaucoup de centres. Ici depuis douze ans. La CPN, je la fais depuis longtemps, parce qu'il n'y avait pas de sage-femme au début."]],
    O2: [["P", "Vingt, vingt-cinq femmes. Nous sommes deux. Le travail est le même depuis des années : on reçoit, on mesure, on examine, on donne les comprimés."]],
    Q1: [["P", "Inscription, poids, tension, examen, comprimés, rendez-vous."]],
    Q2: [["P", "La tension, avec ce vieil appareil — regardez, la poire est réparée avec du ruban. Il marche, mais il faut s'y reprendre à deux ou trois fois. Le sucre, nous n'avons jamais eu d'appareil ici. Jamais."]],
    Q3: [["P", "J'en ai vu beaucoup en trente ans. La dernière, il y a quelques mois, une femme à 160 sur 100. Je l'ai référée. Elle est allée, je crois. On ne sait pas toujours."], ["E", "Pouvez-vous me raconter comment cela s'est passé exactement ?"], ["P", "Comme d'habitude. On mesure, on reprend parce que l'appareil n'est pas sûr, on écrit, on dit d'aller à l'hôpital. Le reste ne dépend plus de nous."]],
    Q4: [["P", "Que la tension est haute et qu'il faut aller à l'hôpital."]],
    Q5: [["P", "Elles comprennent qu'il faut aller à l'hôpital. Certaines y vont, d'autres vont d'abord voir les guérisseurs [abavuzi gakondo]. C'est comme ça depuis toujours ici."]],
    Q6: [["P", "Je dis la même chose à toutes. Après trente ans, on a ses phrases."]],
    Q7: [["P", "Une chose parmi les autres. Je mesure, comme on m'a appris."]],
    Q8: [["P", "La tension, oui, ça a toujours fait partie de la CPN. Le sucre, je ne sais pas, on ne l'a jamais fait ici."]],
    Q9: [["P", "L'habitude. Et l'appareil, tant qu'il tient."]],
    Q10: [["P", "Les jours où l'appareil ne donne pas de chiffre. Je recommence, je recommence, et parfois j'abandonne et j'écris ce que j'ai pu lire. Il faudrait un appareil neuf, mais on le demande depuis longtemps."]],
    Q11: [["P", "Les femmes sont comme elles sont. Certaines viennent tôt, d'autres tard. Certaines écoutent, d'autres vont voir le guérisseur. On ne peut pas forcer."]],
    Q12: [["P", "Celles qui vivent loin. Et celles dont la famille fait confiance au guérisseur plus qu'à nous."]],
    Q13: [["P", "On réfère. Après, c'est l'hôpital, et c'est Dieu."]],
    Q14: [["P", "La distance, l'argent, l'habitude. Les femmes d'ici ont toujours accouché comme leurs mères. Ça change lentement."]],
    Q15: [["P", "Pas de formation sur ces maladies. Ma formation, c'était il y a trente ans. On n'en parlait pas."]],
    Q16: [["P", "Ils regardent les chiffres. Ils ne posent pas de questions sur la tension. Ils ne m'ont jamais parlé du sucre."]],
    Q17: [["P", "Un appareil neuf. Pourquoi ? Parce que le mien a trente ans d'âge, comme mon service, et qu'on fatigue tous les deux."]],
    Q18: [["P", "Un appareil, et une formation pour les jeunes. Moi je pars bientôt."]],
    Q19: [["P", "(silence) Normal… Ce n'est pas bien, mais c'est la vie ici. On fait ce qu'on peut avec ce qu'on a. Les choses changent lentement. J'ai vu pire, quand j'ai commencé : il n'y avait même pas d'appareil du tout."], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "Parce qu'en trente ans, j'ai vu que s'inquiéter ne change rien. On mesure, on réfère, et on espère."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "De l'argent du pays, du matériel, et un peu de Dieu."]],
    Q20: [["P", "Non. Formez bien les jeunes, c'est tout."]],
  },
};

export const P21 = {
  journal: "Entretien en kinyarwanda, dans le bureau de la titulaire, éclairé par la fenêtre faute d'électricité ce jour-là. Participante déterminée, concrète, décrit plusieurs initiatives personnelles, dont un cahier de suivi après l'accouchement. Une interruption (agent de santé communautaire venu signaler une femme). Réflexion : cet entretien répond, sans le savoir, à la question laissée ouverte par plusieurs participants de la vague 1 (« on la trouve et on la perd ») ; à rapprocher dans l'analyse sans forcer le parallèle.",
  reponses: {
    O1: [["P", "Sage-femme A1, huit ans de métier. Titulaire ici depuis trois ans — c'est rare qu'une sage-femme soit titulaire, mais il n'y avait personne d'autre. Je fais la CPN, les accouchements, et la gestion."]],
    O2: [["P", "Vingt femmes environ. Nous sommes le centre le plus loin du district. L'électricité vient d'un panneau solaire, et quand le ciel est couvert, on travaille à la lumière de la fenêtre."]],
    Q1: [["P", "Inscription, poids, tension, examen, bandelette urinaire, médicaments, rendez-vous. Et pour les femmes à qui on a trouvé une tension élevée, une inscription dans un cahier à part."]],
    Q2: [["P", "La tension à toutes, avec l'appareil à piles — quand il y a des piles. Il y a des semaines où il n'y en a pas, alors j'en achète moi-même au marché, parce qu'on ne peut pas faire de CPN sans tension. Le sucre, pas d'appareil."]],
    Q3: [["P", "L'an dernier, une femme de trente-trois ans, quatrième grossesse, tension à 162 sur 104 à trente semaines. Référée, hospitalisée, accouchée à l'hôpital. Elle est revenue ici après."], ["E", "Et ensuite ?"], ["P", "C'est là que j'ai commencé le cahier. Elle m'a demandé : « et maintenant, je fais quoi pour ma tension ? ». Je n'avais rien à lui proposer. Alors j'ai ouvert un cahier où j'écris les femmes à qui on a trouvé une tension haute pendant la grossesse, et je leur demande de revenir la faire mesurer à trois mois, à six mois, à un an."]],
    Q4: [["P", "Que sa tension était trop haute, dangereuse pour elle et pour l'enfant, qu'il fallait aller à l'hôpital, et — depuis le cahier — que même après l'accouchement il faudra continuer à la surveiller."]],
    Q5: [["P", "Elles comprennent le danger. L'après, elles le comprennent mieux depuis que je leur donne une date précise : « reviens à la fête de telle date ». Une date, ça se retient mieux qu'un conseil."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Que sa tension la concerne toute sa vie, pas seulement pendant la grossesse."]],
    Q6: [["P", "Oui. Avec celles qui vivent très loin, je passe par l'agent de santé communautaire [umujyanama w'ubuzima] du village : je lui explique, et il répète à la femme et à la famille. Il parle leur langue de tous les jours mieux que moi."]],
    Q7: [["P", "Pour moi c'est une priorité, parce qu'ici une prééclampsie trouvée tard, c'est une femme qu'on ne peut pas transporter à temps. Plus on est loin, plus le dépistage compte."]],
    Q8: [["P", "Oui. Et même au-delà de la grossesse : c'est pour ça que j'ai fait le cahier."]],
    Q9: [["P", "Les agents de santé communautaire, qui me signalent les femmes qui ne reviennent pas. Et le cahier, qui me permet de ne pas les oublier."]],
    Q10: [["P", "Les semaines sans piles. Et le sucre, toujours."], ["E", "Comment l'expliquez-vous ?"], ["P", "Les piles, personne n'y pense dans les commandes : on commande des appareils, pas les piles qui les font marcher. Le sucre, nous sommes trop loin pour qu'on pense à nous."]],
    Q11: [["P", "Ici toutes les femmes sont loin de tout. La différence, c'est entre celles qui ont un agent communautaire actif dans leur village et les autres."]],
    Q12: [["P", "Celles des villages sans agent actif, et celles qui ont des grossesses rapprochées et beaucoup d'enfants à la maison : elles ne peuvent pas revenir facilement."]],
    Q13: [["P", "Je confirme, je réfère, je cherche le transport — c'est le plus long. Et j'écris dans le cahier. Mon rôle ne s'arrête pas à la référence : il continue avec le cahier, après l'accouchement."]],
    Q14: [["P", "La distance, avant tout. Il y a des femmes à trois heures de marche. Et l'argent, et les enfants."]],
    Q15: [["P", "Pas de formation. J'ai appris avec les cas, et en appelant une amie sage-femme à l'hôpital quand je doute."]],
    Q16: [["P", "Le district vient rarement, c'est loin. Quand ils viennent, ils regardent les registres officiels. Le cahier de suivi, je leur ai montré : ils ont dit que c'était bien, mais que ce n'était pas un outil officiel."]],
    Q17: [["P", "Que le suivi après l'accouchement devienne officiel, avec un support. Pourquoi ? Parce que mon cahier repose sur moi. Si je pars, il s'arrête. Et pourtant c'est la seule chose ici qui suit ces femmes après la grossesse."]],
    Q18: [["P", "Des piles dans les commandes — ça paraît petit, mais c'est la tension de toutes les femmes. Un glucomètre pour les centres éloignés. Et un outil officiel de suivi après l'accouchement."]],
    Q19: [["P", "Non, ce n'est pas normal. Une femme d'ici a droit à la même chose qu'une femme de Kibungo. Alors j'ai fait ce que je pouvais avec ce que j'avais : le cahier, les piles, les agents. Ça ne remplace pas ce qui manque, mais je ne pouvais pas rester sans rien faire."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "De la distance, du matériel, et de qui est titulaire. C'est ça qui n'est pas juste : que ça dépende de qui est titulaire."]],
    Q20: [["P", "Oui : le suivi après l'accouchement. On parle beaucoup de trouver ; on parle peu de ce qu'on fait après avoir trouvé. Et pour nous, loin de tout, c'est là que tout se joue."]],
  },
};
