// DONNÉES SIMULÉES — P14 (CS06, urbain, rotation du personnel), P15 (CS08,
// rural, agents de santé communautaire, affiche faite main), P16 (CS09, centre
// récemment ouvert, dotation incomplète).
// Les termes en kinyarwanda entre crochets sont ILLUSTRATIFS.

export const P14 = {
  journal: "Entretien en kinyarwanda, dans la salle de planning familial libérée. Participante très jeune dans le métier, réponses brèves au début, plusieurs « je ne sais pas » assumés. S'anime en parlant des collègues partis. Une interruption (stagiaire venu demander une consigne). Réflexion : comme pour P03 en vague 1, la jeunesse professionnelle produit un discours tourné vers ce qui manque plutôt que vers ce qui se fait ; j'ai insisté sur les récits concrets.",
  reponses: {
    O1: [["P", "Infirmière A1, sortie il y a deux ans. Ici depuis un an et demi. On m'a mise à la CPN dès mon arrivée, parce que deux collègues venaient d'être mutés."]],
    O2: [["P", "Beaucoup de femmes, quarante et plus. Nous sommes trois en principe, mais souvent deux, et il y a des stagiaires qui aident aux constantes."]],
    Q1: [["P", "Inscription, constantes au couloir, consultation, examens, médicaments, rendez-vous."]],
    Q2: [["P", "La tension aux constantes, c'est souvent le stagiaire qui la prend. Le sucre, c'est au laboratoire : ils ont l'appareil et quelques bandelettes, cinq je crois. À la première visite, c'est pour toutes. Après, je ne sais pas toujours à qui le refaire. Les collègues qui sont partis savaient ; moi j'ai appris en les regardant, pendant deux mois."], ["E", "Pouvez-vous m'en dire davantage ?"], ["P", "Il y avait une sage-femme qui refaisait le test aux femmes grosses ou qui avaient eu un gros bébé. Je fais pareil. Mais je ne sais pas si c'est la règle complète ou seulement son habitude à elle."]],
    Q3: [["P", "Je n'ai pas encore eu de cas de sucre. Pour la tension, oui, une femme à 150 sur 95. Le stagiaire me l'a dit, j'ai repris, c'était pareil, et j'ai appelé la sage-femme plus ancienne qui a décidé de la référer."]],
    Q4: [["P", "C'est la sage-femme qui a expliqué. Moi j'ai écouté pour apprendre."]],
    Q5: [["P", "Je ne sais pas encore bien. Je pense qu'elles comprennent qu'il faut aller à l'hôpital."]],
    Q6: [["P", "Je dis à peu près la même chose à tout le monde, parce que je ne connais pas encore assez pour adapter. Peut-être que j'en dis moins à celles qui sont pressées."]],
    Q7: [["P", "C'est une étape parmi les autres. Comme je suis nouvelle, j'essaie surtout de ne rien oublier dans la liste."]],
    Q8: [["P", "Oui, je pense. On me l'a appris à l'école."]],
    Q9: [["P", "Avoir une collègue expérimentée à qui demander. Quand elle est là, je suis tranquille."]],
    Q10: [["P", "Quand le stagiaire est seul aux constantes et qu'il y a beaucoup de monde, je ne suis pas sûre que toutes les tensions soient bien prises. Il annonce les chiffres à voix haute dans le couloir, et je ne vérifie pas tout."], ["E", "Comment l'expliquez-vous ?"], ["P", "Il manque des personnes. Les gens partent, on met des nouveaux ou des stagiaires, et chacun apprend sur le tas. Ce qu'une personne savait part avec elle."]],
    Q11: [["P", "Il y a des femmes qui connaissent mieux le centre que moi, qui viennent depuis plusieurs grossesses. Elles savent ce qu'on doit leur faire. Les nouvelles, elles ne savent pas, et moi non plus parfois."]],
    Q12: [["P", "Je ne sais pas encore bien. Peut-être celles qui ne parlent pas beaucoup."]],
    Q13: [["P", "J'appelle la collègue expérimentée et elle décide. Si elle n'est pas là, je réfère avec la fiche. Après, je ne sais pas."]],
    Q14: [["P", "Le travail et l'argent, je pense. Et l'attente ici : elle est longue."]],
    Q15: [["P", "Pas de formation. J'ai appris en regardant les collègues, et la plupart sont partis. Ce que je sais, je le tiens d'une personne qui n'est plus là."]],
    Q16: [["P", "Je ne sais pas. La supervision parle avec le titulaire."]],
    Q17: [["P", "Que les gens restent. Pourquoi ? Parce que chaque fois que quelqu'un part, on recommence à zéro. On peut former une personne, mais si elle part l'année suivante, la formation part avec elle."]],
    Q18: [["P", "Qu'on écrive les règles quelque part, au lieu de les apprendre de bouche à oreille. Une fiche, un classeur. Pour que ce qu'on sait reste dans le centre et pas dans la tête de celui qui part."]],
    Q19: [["P", "(silence) Je ne sais pas encore. Je vois que ce n'est pas égal. Mais je suis nouvelle, je ne sais pas si c'est normal partout ou seulement ici."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "De qui est là ce jour-là. Si la collègue expérimentée est là, c'est mieux fait. Si c'est moi et le stagiaire, c'est moins bien. Ça dépend de nous, de qui on est."]],
    Q20: [["P", "Non. Peut-être que vous devriez parler aux collègues qui sont partis, ils savaient plus de choses que moi."]],
  },
};

export const P15 = {
  journal: "Entretien en kinyarwanda, dans la salle de consultation. Participante enjouée, pratique, raconte avec précision ses initiatives. Montre l'affiche qu'elle a dessinée avec sa collègue. Aucune interruption. Ne sait pas si elle a reçu une formation sur les MNT : se souvient d'une journée « sur la nutrition et la tension » sans pouvoir la qualifier — consigné tel quel dans la fiche. Réflexion : risque de valoriser les initiatives par mes réactions ; je me suis tenu aux relances neutres.",
  reponses: {
    O1: [["P", "Sage-femme A1, sept ans de métier, ici depuis cinq ans. La CPN et la maternité."]],
    O2: [["P", "Vingt-cinq, trente femmes. Une particularité chez nous : les agents de santé communautaire [abajyanama b'ubuzima] passent presque tous les jours, surtout les animatrices de santé maternelle, les ASM. Elles nous amènent la liste des femmes enceintes du village, elles raccompagnent des femmes, elles nous disent qui n'est pas revenue."]],
    Q1: [["P", "Inscription, poids, tension, examen, bandelette urinaire, médicaments, conseils avec l'affiche, rendez-vous."]],
    Q2: [["P", "La tension, à toutes. Le sucre, le glucomètre du laboratoire est en panne depuis l'an dernier. Quand je soupçonne quelque chose, je réfère pour une glycémie et je demande à l'ASM du village, l'animatrice de santé maternelle, de vérifier qu'elle y est allée."], ["E", "Comment cela se passe-t-il exactement ?"], ["P", "Je lui donne le nom, elle passe la voir dans la semaine. Si elle n'est pas allée, elle me le dit, et elle essaie de comprendre pourquoi : l'argent, le mari, la distance. Parfois elle arrive à arranger les choses, parfois non. Mais au moins je sais."]],
    Q3: [["P", "Une femme, deuxième grossesse, tension à 155 sur 100, sans protéines. Je l'ai référée. Elle n'y est pas allée : le mari était en voyage et elle n'avait pas l'argent. L'ASM est passée, elle a parlé avec la famille, et le frère de la femme l'a accompagnée trois jours après. Elle avait une hypertension de grossesse, traitée."], ["E", "Et ensuite ?"], ["P", "Sans l'ASM, je ne l'aurais jamais su. Elle serait revenue à huit mois, ou pas du tout."]],
    Q4: [["P", "Je lui ai expliqué avec l'affiche : regardez, ici, les maux de tête, le visage gonflé — ce sont les signes. Votre tension est haute, c'est pour ça qu'il faut aller voir le médecin."]],
    Q5: [["P", "Avec l'affiche, beaucoup mieux. Avant, je parlais et je voyais bien qu'elles hochaient la tête par politesse. Avec les dessins, elles posent des questions, elles montrent du doigt."], ["E", "Pouvez-vous m'en dire davantage sur l'affiche ?"], ["P", "Nous n'avions aucune affiche. Alors avec ma collègue, on a pris une grande feuille et on a dessiné les signes de danger : une femme qui se tient la tête, un visage gonflé, une femme qui saigne. Avec quelques mots en kinyarwanda. Ce n'est pas beau, mais elles comprennent."]],
    Q6: [["P", "Oui. Avec l'affiche, j'explique pareil à toutes, c'est ça l'avantage : l'image est la même pour celle qui sait lire et pour celle qui ne sait pas. Mais avec celles qui ont été à l'école, je parle aussi de l'alimentation, du sel."]],
    Q7: [["P", "Important. Je l'ai mis au même niveau que le reste. L'affiche, c'est un peu pour ça : pour que la tension ne soit pas oubliée."]],
    Q8: [["P", "Oui. Et avec les agents communautaires, on peut même aller plus loin que le centre : ils voient les femmes dans les villages."]],
    Q9: [["P", "Les agents de santé communautaire, d'abord. L'affiche. Et le tensiomètre qui marche."]],
    Q10: [["P", "Pour le sucre, toujours, puisque l'appareil du laboratoire est en panne. Et quand l'agent du village n'est pas actif — tous ne le sont pas — je perds la trace des femmes que j'ai référées."]],
    Q11: [["P", "Il y a les villages où l'agent communautaire est actif et ceux où il ne l'est pas. La différence est grande : dans les premiers, les femmes viennent plus tôt et reviennent. Ce n'est pas la femme qui change, c'est l'agent."]],
    Q12: [["P", "Celles des villages sans agent actif. Et celles dont le mari décide de tout."]],
    Q13: [["P", "Je réfère, je note dans mon cahier, et je préviens l'agent du village. Mon rôle continue grâce à lui : il est mes yeux après la référence."]],
    Q14: [["P", "La distance et l'argent. Et dans les villages sans agent, personne ne leur dit qu'il faut venir tôt."]],
    Q15: [["P", "Je ne sais pas exactement. Il y a eu une journée au district, il y a quelques années, sur la nutrition et la tension. Je ne sais pas si c'était une formation sur les maladies non transmissibles. Le diabète de grossesse, je ne m'en souviens pas."]],
    Q16: [["P", "La supervision a vu l'affiche une fois, ils ont dit que c'était bien. Mais ils n'ont rien demandé de plus, ni sur la tension ni sur le sucre."]],
    Q17: [["P", "Former et soutenir tous les agents communautaires, pas seulement quelques-uns. Pourquoi ? Parce qu'ils sont là où nous ne sommes pas. Un appareil reste au centre ; l'agent, lui, va chez la femme."]],
    Q18: [["P", "Qu'on donne aux centres des affiches vraies, dessinées pour des gens qui lisent peu. Et qu'on paie un peu mieux les agents communautaires, parce qu'ils font beaucoup avec rien."]],
    Q19: [["P", "Non, ce n'est pas normal. Mais je ne veux pas dire seulement que c'est le système. Chez nous, avec une feuille et des crayons, et avec les agents, on a réduit une partie de la différence. Ce n'est pas tout — le sucre, on ne peut rien. Mais il y a des choses qu'on peut faire ici."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "Du matériel, de l'agent du village, et de nous. Les trois."]],
    Q20: [["P", "Oui : les agents de santé communautaire. On parle toujours du centre, mais la moitié du dépistage se joue dans les villages."]],
  },
};

export const P16 = {
  journal: "Entretien en kinyarwanda, dans le bureau du titulaire d'un centre ouvert depuis peu. Participant posé, centré sur la mise en place : dotation, registres, personnel. Nombreuses références à ce qui est « prévu » ou « en attente ». Aucune interruption. Réflexion : le participant a une longue expérience mais une expérience récente de la CPN ; le discours sur le dépistage reste général, celui sur l'organisation est précis.",
  reponses: {
    O1: [["P", "Infirmier A2, plus de vingt ans de service, surtout au curatif et en santé communautaire. J'ai été nommé titulaire ici à l'ouverture du centre, il y a un an et demi. Avant, c'était un poste de santé sans consultation prénatale."]],
    O2: [["P", "Calme : dix, quinze femmes. La population continue d'aller à l'ancien centre, où elle a ses habitudes. Nous sommes deux. Le bâtiment est neuf, mais il nous manque encore des choses."]],
    Q1: [["P", "Inscription dans le cahier, poids, tension, examen, médicaments, rendez-vous."], ["E", "Vous dites « le cahier » ?"], ["P", "Le registre officiel de CPN n'est pas encore arrivé. Nous avons tracé les colonnes dans un cahier, à la règle, en copiant le modèle d'un autre centre."]],
    Q2: [["P", "La tension, avec l'appareil neuf, à toutes. Le sucre, le glucomètre est prévu dans la dotation du laboratoire, mais il n'est pas arrivé. Les bandelettes urinaires non plus."]],
    Q3: [["P", "Une seule fois depuis l'ouverture : une femme à 158 sur 96. Je l'ai référée en écrivant sur son carnet, puisque nous n'avons pas encore les fiches de référence. Je ne sais pas ce qu'elle est devenue."]],
    Q4: [["P", "Que sa tension était élevée et qu'elle devait aller à l'hôpital."]],
    Q5: [["P", "Je pense qu'elles comprennent l'essentiel."]],
    Q6: [["P", "Je dis la même chose à toutes. Comme nous avons peu de monde, j'ai le temps."], ["E", "Pouvez-vous me donner un exemple ?"], ["P", "Avec dix femmes le matin, je peux parler à chacune aussi longtemps que nécessaire. C'est peut-être le seul avantage d'un centre qui démarre."]],
    Q7: [["P", "Une étape de la consultation. Pour l'instant, mon souci principal est que le centre fonctionne : les registres, la dotation, faire venir la population."]],
    Q8: [["P", "Oui, c'est dans les directives."]],
    Q9: [["P", "Le matériel neuf, quand il est là, et le temps, puisque nous avons peu de femmes."]],
    Q10: [["P", "Le sucre, toujours, puisque l'appareil n'est pas livré. Et sans bandelettes urinaires, je ne peux même pas chercher les protéines quand la tension est haute."], ["E", "Comment l'expliquez-vous ?"], ["P", "La dotation arrive par morceaux. Le bâtiment d'abord, puis le mobilier, puis l'équipement de base. Les consommables et les registres viennent en dernier. On nous dit que tout est commandé."]],
    Q11: [["P", "Il y a celles qui viennent chez nous parce que c'est plus près, et celles qui continuent d'aller à l'ancien centre. Pour celles qui viennent, le service est encore incomplet."]],
    Q12: [["P", "Je ne sais pas encore. Le centre est trop jeune."]],
    Q13: [["P", "Je réfère par écrit sur le carnet. Je n'ai pas de retour."]],
    Q14: [["P", "L'habitude d'aller à l'ancien centre, et la confiance qui ne s'est pas encore construite avec nous."]],
    Q15: [["P", "Pas de formation sur ces maladies. On nous a formés à l'ouverture sur la gestion du centre et les rapports."]],
    Q16: [["P", "Pour l'instant, le district suit surtout l'ouverture : le personnel, les bâtiments, la fréquentation. Le contenu de la CPN viendra après, je suppose."]],
    Q17: [["P", "Que la dotation soit complète. Pourquoi ? Parce que tant qu'il manque le glucomètre et les bandelettes, je ne peux faire qu'une moitié de dépistage, même avec toute la bonne volonté."]],
    Q18: [["P", "Qu'on n'ouvre pas un centre avant qu'il soit équipé. Ou qu'on dise clairement à la population ce qu'on peut faire et ce qu'on ne peut pas encore faire."]],
    Q19: [["P", "(silence) C'est un centre qui commence. Je ne dirais pas que c'est normal, mais c'est temporaire, j'espère. Les femmes qui viennent maintenant ont moins que celles qui viendront dans un an. C'est le prix d'un centre neuf."], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "Parce que tout est en route. Mais je comprends que pour la femme enceinte aujourd'hui, « en route » ne veut rien dire : elle n'a qu'une grossesse."]],
    Q20: [["P", "Non. Peut-être revenir dans un an, quand le centre sera complet."]],
  },
};
