// DONNÉES SIMULÉES — P11 (CS01, urbain, bien doté), P12 (CS04, titulaire
// rural), P13 (CS05, enclavé, bandelettes périmées).
// Convention : ["E", …] = enquêteur ; ["P", …] = participant. Les termes en
// kinyarwanda entre crochets sont ILLUSTRATIFS et doivent être relus par un
// locuteur natif.

export const P11 = {
  journal: "Entretien en français, à la demande de la participante, dans une salle de consultation libérée. Participante assurée, précise, cite des chiffres de stock de mémoire. C'est le seul entretien où le dépistage glycémique est décrit comme une pratique courante et non comme une impossibilité ; j'ai dû veiller à ne pas laisser transparaître ma surprise. Aucune interruption. Réflexion : ce centre étant le mieux doté, il y avait un risque que l'entretien prenne la forme d'une démonstration de bonne pratique ; les questions Q10 à Q12 ont été les plus utiles pour en sortir.",
  reponses: {
    O1: [["P", "Sage-femme A1, formée à Kigali. J'ai fait deux ans dans un hôpital de district, puis je suis venue ici, il y a sept ans. La CPN est mon poste principal depuis cinq ans. L'an dernier, j'ai suivi la formation du district sur les maladies non transmissibles, trois jours."]],
    O2: [["P", "Beaucoup de monde : quarante, cinquante femmes certains jours. Mais nous sommes organisées en trois postes — les constantes, la consultation, et un poste pour les examens et le conseil. Une femme passe de l'un à l'autre. Si un poste se vide, on le voit tout de suite."]],
    Q1: [["P", "Accueil, inscription, puis la salle des constantes : poids, tension, et à la première visite la taille et le périmètre du bras. Ensuite la consultation : signes de danger, examen, hauteur utérine, bruits du cœur. Ensuite le laboratoire, juste à côté, avec le bon que je remplis : sérologies et glycémie ; la bandelette urinaire, nous la faisons nous-mêmes. Enfin le conseil et le rendez-vous."]],
    Q2: [["P", "La tension, à toutes, aux constantes. La glycémie, au laboratoire du centre, sur mon bon : à la première visite, pour toutes ; ensuite pour les femmes qui ont un facteur de risque : surpoids, antécédent de gros bébé ou de diabète dans la famille, sucre dans les urines, âge. Le laboratoire a l'appareil et des bandelettes — en ce moment quarante-huit ; il y a une fiche de stock, et quand on descend sous vingt, on commande. Nous avons aussi un glucomètre à la CPN pour les urgences. Et si un jour le test n'a pas pu se faire, on écrit « glycémie à refaire » sur le carnet, et on la fait au rendez-vous suivant."], ["E", "Pouvez-vous m'en dire davantage ?"], ["P", "Je sais que ce n'est pas comme ça partout. J'ai des collègues de promotion dans d'autres centres qui n'ont jamais vu une bandelette. Ici on a eu de la chance avec un titulaire qui suit le stock de près, et peut-être aussi avec notre position : on est à côté du district, quand on appelle, on nous répond."], ["E", "Et entre vingt-quatre et vingt-huit semaines ?"], ["P", "Pas pour toutes. Le protocole parle d'une épreuve à ce moment-là, mais ici personne ne la fait : il faudrait que la femme vienne à jeun et reste deux heures. Alors on refait une glycémie simple à celles qui ont un risque. Les autres, on leur fait confiance."]],
    Q3: [["P", "Le mois dernier, une femme de trente-six ans, quatrième grossesse, vingt-six semaines, en surpoids. Sucre dans les urines. Le laboratoire a fait la glycémie le matin même, elle était élevée. Je l'ai référée avec la fiche. Une semaine après, le volet de retour de l'hôpital est revenu : diabète gestationnel confirmé, régime, contrôles. Elle est suivie conjointement maintenant."], ["E", "Et ensuite ?"], ["P", "Ensuite elle revient chez nous entre ses rendez-vous à l'hôpital, et grâce au volet de retour je sais ce qu'on lui a prescrit. C'est la première fois depuis que je travaille que j'ai ce genre de retour régulièrement. Ça change tout : je ne devine plus."]],
    Q4: [["P", "Je lui ai expliqué que son corps avait du mal à utiliser le sucre pendant la grossesse, que cela pouvait faire grossir le bébé et compliquer l'accouchement, et que ça se soignait d'abord par l'alimentation. Je lui ai montré l'affiche, celle avec les assiettes. Et je lui ai dit que ce diabète-là disparaît souvent après l'accouchement, mais qu'il prévient d'un risque pour plus tard."]],
    Q5: [["P", "Avec l'affiche, je crois qu'elles comprennent mieux, parce qu'elles voient. Sans image, elles retiennent seulement « il y a un problème ». Avec l'image, elles retiennent ce qu'il faut changer. Mais ce qu'elles comprennent mal, même ici, c'est le « plus tard ». L'avenir à dix ans, quand on a quatre enfants à nourrir aujourd'hui, ça ne pèse pas beaucoup."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Qu'elle revienne se faire contrôler après l'accouchement. C'est la seule chose qui compterait vraiment à long terme, et c'est celle qu'on obtient le moins."]],
    Q6: [["P", "Oui. Même ici, avec tout ce qu'on a, j'adapte selon le temps. Le matériel ne crée pas de temps. Nous avons les bandelettes, mais quand il y a cinquante femmes, l'explication est plus courte pour celles qui passent en fin de matinée. Le matériel règle l'inégalité du test ; il ne règle pas celle de l'explication."], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "Parce que je l'ai vu changer. Avant les bandelettes, on disait « allez faire le test à l'hôpital ». Maintenant on le fait ici, à toutes celles qui en ont besoin. Mais l'explication après le test, elle, dépend toujours de l'heure. Ça, aucun approvisionnement ne l'a changé."]],
    Q7: [["P", "Ici, c'est une partie normale du travail, au même rang que le reste. Je dirais même que c'est devenu une fierté de l'équipe. Mais je mesure ce que ça doit à nos moyens : dans un centre sans bandelettes, je crois que je penserais comme les collègues qui me disent que le diabète « n'est pas leur travail »."]],
    Q8: [["P", "Oui, sans hésitation. C'est le moment où on voit la femme. Et je pense que la preuve qu'on peut le faire, c'est que nous le faisons. Si on peut le faire ici, alors ce n'est pas une question de capacité des sages-femmes, c'est une question de moyens."]],
    Q9: [["P", "Trois choses : l'organisation en postes, le stock suivi, et le volet de retour de l'hôpital. Le troisième est le moins visible et peut-être le plus important, parce que sans lui le dépistage s'arrête à la porte."]],
    Q10: [["P", "Même ici, ça arrive. Le mois de juillet, le volet de retour n'est pas revenu pendant trois semaines — un changement de personnel à l'hôpital. Et pendant ce temps, j'ai eu deux femmes référées dont je n'ai rien su. On voit à quel point tout repose sur une feuille et sur la personne qui la remplit de l'autre côté."]],
    Q11: [["P", "Oui. Chez nous, la différence ne se fait plus sur le test : toutes ont leur glycémie à la première visite, et celles qui ont un risque l'ont de nouveau. Elle se fait sur l'heure d'arrivée et sur la capacité à revenir. Celle qui travaille au marché revient moins, même si on lui a tout expliqué."]],
    Q12: [["P", "Celles qui viennent d'autres secteurs, plus loin, parce que notre centre est connu. Elles viennent une fois, parce qu'on leur a dit qu'ici le test du sucre ne manque jamais, et puis elles ne peuvent pas revenir pour le suivi. Nous attirons des femmes que nous ne pouvons pas suivre."]],
    Q13: [["P", "Glycémie ou tension confirmée, fiche de référence à deux volets, et la femme part. Le second volet revient — pas toujours, mais souvent. Mon rôle continue donc après la référence : je reçois la conduite à tenir et je la revois entre ses visites à l'hôpital. Il y a aussi une chose nouvelle : certaines femmes, une fois le diagnostic posé, s'achètent un tensiomètre électronique ou un glucomètre et mesurent à la maison. Elles reviennent avec un cahier de chiffres, et c'est précieux. Mais ce sont des femmes de fonctionnaires ou de commerçants ; la femme qui cultive ne le pourra jamais, et c'est elle qui habite le plus loin."]],
    Q14: [["P", "Le travail, le coût du transport pour celles qui viennent de loin, et pour certaines la peur qu'on leur trouve quelque chose. Une femme m'a dit une fois : « si je ne viens pas, on ne me trouvera pas de maladie ». Ce n'est pas de l'ignorance, c'est une manière de se protéger."]],
    Q15: [["P", "Le centre m'a préparée par l'organisation qui existait avant moi, et le district par la formation de l'année dernière. Mais je dirais que c'est surtout l'équipe qui forme : chaque nouvelle personne passe une semaine à chaque poste avec quelqu'un d'expérimenté."]],
    Q16: [["P", "Notre titulaire a réussi à faire inscrire les glycémies dans le rapport mensuel du centre, même si le district ne le demande pas. Je pense que c'est pour ça que le stock suit : quand il manque, ça se voit dans notre propre rapport. Au niveau du district, je ne sais pas si quelqu'un regarde cette ligne."]],
    Q17: [["P", "Que le volet de retour devienne obligatoire pour l'hôpital, pas une bonne volonté. Pourquoi celui-là ? Parce que nous avons déjà le reste. Ce qui nous manque n'est plus le test, c'est la certitude de savoir ce que devient la femme."]],
    Q18: [["P", "Qu'ils regardent ce qui marche ici et qu'ils le donnent aux autres centres, en commençant par les plus éloignés. Je ne veux pas que mon centre soit un modèle qu'on vient visiter : je veux qu'il devienne normal."]],
    Q19: [["P", "Non. Mais je veux préciser où se trouve ce qui n'est pas normal. À l'intérieur de mon centre, l'inégalité est devenue petite — elle reste dans l'explication, dans l'heure. Entre mon centre et un centre rural à vingt kilomètres, elle est énorme. Une femme d'ici a son test même un jour où il manque quelque chose, parce qu'on le rattrape ; une femme de là-bas, si elle tombe le mois de la rupture ou de la panne, ne l'aura jamais. Ce n'est pas normal, et ce n'est pas dans mon pouvoir."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "De l'endroit où l'on vit, d'abord. Et à l'intérieur d'un même endroit, du temps disponible. Le premier se décide au district ; le second, un peu, chez nous."]],
    Q20: [["P", "Oui. Ne présentez pas mon centre comme la preuve que tout est possible. Présentez-le comme la preuve que c'est possible AVEC des moyens. La nuance est importante pour mes collègues des centres ruraux : ils ne font pas moins bien que nous, ils ont moins."]],
  },
};

export const P12 = {
  journal: "Entretien en kinyarwanda, dans le bureau du titulaire. Participant jeune pour une fonction de titulaire, partagé entre son rôle de gestionnaire et celui de soignant ; revient spontanément sur la charge administrative. Une interruption (appel du district, cinq minutes, enregistrement suspendu). Ton franc, peu défensif, reconnaît sans difficulté ses lacunes sur le diabète gestationnel. Réflexion : le participant a demandé à la fin si ses réponses seraient transmises au district ; j'ai rappelé la confidentialité et l'absence de toute restitution nominative.",
  reponses: {
    O1: [["P", "Infirmier A1. J'ai travaillé quatre ans au curatif, puis on m'a nommé titulaire ici il y a trois ans. Comme titulaire d'un petit centre, je fais la CPN deux ou trois matins par semaine, et le reste du temps les rapports, les commandes, les réunions."]],
    O2: [["P", "Vingt-cinq, trente femmes. Nous sommes deux. Quand je suis à la CPN, ça va. Quand je suis appelé — une réunion, un appel du district, un rapport à rendre — ma collègue est seule. Et les rapports, il y en a beaucoup."]],
    Q1: [["P", "Inscription, poids, tension, attente, examen, médicaments, rendez-vous. La procédure normale."]],
    Q2: [["P", "La tension au début, à toutes quand nous sommes deux. Le sucre, on fait le bon pour toutes à la première visite et le laboratoire le fait. Mais nous n'avons qu'un laborantin ; quand il est en formation ou malade, le test ne se fait pas, et nous n'avons pas de glucomètre à la CPN. Et je vais être honnête : même si on m'en donnait un demain, je ne saurais pas m'en servir, ni à partir de quel chiffre m'inquiéter chez une femme enceinte. Je n'ai jamais été formé là-dessus."]],
    Q3: [["P", "Une femme, il y a quelques mois, tension à 160 sur 100 au deuxième trimestre. Nous avons repris, c'était pareil. Je l'ai référée. Je ne sais pas ce qu'elle est devenue : elle n'est pas revenue chez nous, et l'hôpital ne nous écrit pas."], ["E", "Comment l'avez-vous vécu ?"], ["P", "Comme d'habitude, malheureusement. On réfère et on ne sait pas. On finit par ne plus se poser la question, et je ne suis pas sûr que ce soit bien."]],
    Q4: [["P", "Que sa tension était trop haute, que c'était dangereux pour elle et pour l'enfant, qu'elle devait aller à l'hôpital vite. Le minimum, je pense."]],
    Q5: [["P", "Qu'il y a un danger. Le détail, je ne crois pas, mais je ne suis pas sûr de bien l'expliquer moi-même."]],
    Q6: [["P", "Je pense que j'explique pareil à tout le monde, mais en vérité ça dépend surtout de si je suis pressé. Les jours de rapport, je suis pressé."]],
    Q7: [["P", "Comme titulaire, je vois le travail par les rapports. Et dans les rapports, la tension n'apparaît pas. Alors c'est une chose que l'on fait parce que c'est dans la fiche, pas une chose que l'on suit. Ce que je suis vraiment, ce sont les chiffres qu'on me demande."]],
    Q8: [["P", "Oui, ça devrait. Mais aujourd'hui, dans la pratique, c'est une étape de la fiche plus qu'un dépistage."]],
    Q9: [["P", "Le tensiomètre marche, et ma collègue est sérieuse. Quand elle est aux constantes, la tension est prise à tout le monde."]],
    Q10: [["P", "Les jours où je suis appelé ailleurs et où ma collègue fait tout seule. La tension est prise, je crois, mais l'explication est réduite au minimum. Et pour le sucre, ce sont les jours où le laborantin est absent ; ces jours-là, on ne le fait pas, et on ne rappelle pas ces femmes."]],
    Q11: [["P", "Il y a celles qui viennent régulièrement et celles qu'on voit une fois ou deux. Avec les premières, on a le temps de tout faire au fil des visites. Avec les secondes, on fait ce qu'on peut en une fois."]],
    Q12: [["P", "Celles qui viennent de loin et qui n'ont pas la mutuelle [mituweli] à jour. Je sais que la référence sera difficile pour elles."]],
    Q13: [["P", "On confirme, on remplit la fiche, on réfère. Mon rôle s'arrête là, parce qu'il n'y a pas de retour."]],
    Q14: [["P", "La distance, le coût, et les travaux des champs. Et je pense aussi qu'on ne leur explique pas assez, à la première visite, pourquoi il faut revenir."]],
    Q15: [["P", "Pas du tout pour le diabète. Pour la tension, la formation de base. On parle d'une formation du district depuis deux ans ; je n'ai pas été appelé."]],
    Q16: [["P", "Au district, les réunions portent sur les indicateurs : CPN1, CPN4, accouchements, vaccination, planning. Je n'ai jamais entendu parler de la tension en réunion. Si c'était demandé dans le rapport, je m'en occuperais — c'est ce qui organise mon travail."]],
    Q17: [["P", "Une formation pour moi et ma collègue, sur les deux maladies. Pourquoi ? Parce qu'on ne peut pas réclamer un appareil qu'on ne saurait pas utiliser. D'abord savoir."]],
    Q18: [["P", "Moins de rapports, ou des rapports qui comptent ce qui compte. Je passe plus de temps à remplir des tableaux qu'à voir des femmes enceintes. Si la tension doit être importante, qu'elle soit dans le tableau ; et qu'on enlève autre chose."]],
    Q19: [["P", "Non, ce n'est pas normal. Mais comme titulaire je vois bien que je n'ai pas de levier : je ne décide ni du matériel, ni de la formation, ni du nombre de personnes. Ce que je peux décider, c'est de passer plus de temps à la CPN et moins aux rapports. Et ça, je ne le fais pas assez, parce que les rapports sont vérifiés et la CPN non."]],
    Q20: [["P", "Peut-être ceci : les titulaires des petits centres sont devenus des secrétaires. On nous forme à remplir des rapports, pas à soigner mieux. Si votre travail pouvait dire ça poliment, ce serait utile."], ["E", "Autre chose ?"], ["P", "Les campagnes. L'an dernier, pendant la semaine des maladies non transmissibles, l'équipe du district a fait un dépistage gratuit au marché : tension, sucre, poids. Deux femmes enceintes de notre zone avaient une tension élevée sans le savoir. On ne l'a appris que parce que l'une d'elles est venue nous montrer son papier. Ces campagnes nous aident, mais elles ne pensent pas aux femmes enceintes, et elles ne nous envoient pas les résultats."]],
  },
};

export const P13 = {
  journal: "Entretien en kinyarwanda, dans la salle de consultation. Participante expérimentée, calme, raconte volontiers. Aborde spontanément le recours aux remèdes traditionnels, sur un ton dénué de mépris, en distinguant ce qu'elle observe de ce qu'elle suppose. Aucune interruption. Réflexion : j'ai craint que le thème des remèdes traditionnels ne glisse vers un registre de jugement sur les femmes ; la participante l'a elle-même évité, ce qui doit être restitué tel quel. Comme toujours, ces propos sont des représentations professionnelles, non une description de pratiques réelles.",
  reponses: {
    O1: [["P", "Sage-femme A1, plus de quinze ans de métier. J'ai travaillé dans deux autres centres avant celui-ci. Ici, la CPN et les accouchements depuis neuf ans. En 2021 j'ai eu la formation sur les maladies non transmissibles."]],
    O2: [["P", "Calme en saison sèche : quinze à vingt-cinq femmes. En saison des pluies, beaucoup moins, parce que la route devient impraticable et que les femmes des collines ne peuvent pas descendre. Il y a des semaines où on voit cinq femmes."]],
    Q1: [["P", "Inscription, poids, tension, examen, médicaments, conseils, rendez-vous. Et à la première visite, je prends plus de temps, parce que je sais que certaines ne reviendront pas avant longtemps à cause de la route."]],
    Q2: [["P", "La tension, à toutes. Le sucre… c'est une histoire. Normalement on fait le bon pour toutes à la première visite. Le laboratoire a un glucomètre qui marche. Il a des bandelettes — trente. Mais elles sont périmées depuis mai. Alors il ne peut pas les utiliser. L'appareil est là, les bandelettes sont là, et le test ne se fait pas."], ["E", "Qu'est-ce que cela vous fait ?"], ["P", "C'est presque pire que de ne rien avoir. Quand on n'a rien, on n'y pense plus. Quand on a tout sous les yeux et qu'on ne peut pas s'en servir, on y pense à chaque femme."]],
    Q3: [["P", "En saison des pluies l'an dernier, une femme de trente ans, troisième grossesse, trente-trois semaines, tension à 165 sur 105, des protéines. Il fallait la référer, mais la route était coupée. Nous avons appelé l'ambulance, elle ne pouvait pas monter. Elle est descendue à pied avec son mari jusqu'à la route goudronnée, une heure et demie, et l'ambulance l'a prise là-bas."], ["E", "Et ensuite ?"], ["P", "Elle a été prise en charge. Mais je ne me suis pas reposée de la journée. Une femme en prééclampsie qui marche une heure et demie sous la pluie… Elle s'en est sortie. On a eu de la chance."]],
    Q4: [["P", "Je lui ai expliqué que la tension était trop forte, que son sang poussait trop fort, que cela pouvait provoquer des convulsions [kugagara], et qu'il ne fallait pas attendre. Je lui ai dit de ne pas boire de remèdes en attendant."], ["E", "Vous avez employé le mot « remèdes », qu'entendez-vous par là ?"], ["P", "Certaines femmes, quand on leur dit que leur tension est haute, vont d'abord voir un guérisseur [umuvuzi gakondo] ou boivent des plantes qu'on leur prépare à la maison. Je ne leur en veux pas : l'hôpital est loin, le guérisseur est à côté et il les connaît. Mais je leur demande de ne pas attendre le résultat des plantes pour partir."]],
    Q5: [["P", "Elles comprennent le danger quand elles ont mal. Quand elles n'ont rien, c'est plus difficile : une maladie qui ne fait pas mal, on ne la croit pas tout à fait. Et je pense que pour certaines, le guérisseur explique mieux que nous, parce qu'il utilise leurs mots."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Que les deux peuvent aller ensemble — elle peut garder ses croyances, mais il faut qu'elle vienne aussi chez nous à temps."]],
    Q6: [["P", "Oui. J'adapte surtout à ce que je sais de la femme : si je sais qu'elle va d'abord voir le guérisseur, je ne lui dis pas que c'est mal, je lui dis de venir quand même. Si je la critique, elle ne reviendra pas. Avec celles qui ont été à l'école, je parle des chiffres ; avec les autres, je parle avec des images."]],
    Q7: [["P", "Important. La tension est ce qui m'inquiète le plus ici, parce qu'avec la route, une prééclampsie trouvée tard est une catastrophe. Le sucre, je le mettrais aussi en haut si je pouvais le faire."]],
    Q8: [["P", "Oui. Surtout chez nous : la femme vient à la CPN, et ensuite on ne la voit plus pendant des années. C'est notre seule chance."]],
    Q9: [["P", "Le tensiomètre électronique, fiable. La formation de 2021. Et l'expérience : je sais repérer une femme fatiguée, gonflée, avant même de mesurer."]],
    Q10: [["P", "Les bandelettes périmées, depuis mai. Et la saison des pluies, où les femmes ne viennent pas du tout : là, il n'y a pas de dépistage parce qu'il n'y a pas de femmes."], ["E", "Comment l'expliquez-vous ?"], ["P", "Les bandelettes, c'est l'approvisionnement : on nous a livré un lot qui expirait vite, et le suivant n'est pas venu. La pluie, c'est la route. Ni l'un ni l'autre ne dépend de nous."]],
    Q11: [["P", "Oui. Celles qui vivent près de la route et celles des collines. Les premières viennent régulièrement ; les secondes viennent deux fois dans la grossesse si tout va bien. Pour elles, chaque visite doit tout faire."]],
    Q12: [["P", "Celles des collines en saison des pluies. Et celles dont la famille préfère le guérisseur — non pas parce qu'elles refusent, mais parce que la décision ne leur appartient pas toujours."]],
    Q13: [["P", "Confirmer, référer, appeler l'ambulance, et en saison des pluies trouver par où la faire descendre. Mon rôle va jusqu'à la route goudronnée, souvent. Après, je n'ai pas de retour, sauf si je téléphone."]],
    Q14: [["P", "La route, la pluie, le coût, et l'idée qu'une grossesse sans douleur n'a pas besoin de soignant. Et certaines vont d'abord chez le guérisseur et viennent chez nous quand ça ne s'arrange pas."]],
    Q15: [["P", "La formation de 2021 du district. Le centre, non. Et depuis, rien : les seuils pour le diabète de grossesse, je les ai notés dans un carnet pour ne pas les oublier, puisque je ne les utilise pas."]],
    Q16: [["P", "Ils regardent le nombre de visites. Quand j'ai signalé les bandelettes périmées, on m'a répondu qu'un lot arriverait. Il n'est pas arrivé. Je crois que pour eux ce n'est pas urgent, parce que ça ne se voit dans aucun chiffre."]],
    Q17: [["P", "Des bandelettes valides, livrées régulièrement, et pas des lots qui expirent dans deux mois. Pourquoi ? Parce que j'ai déjà tout le reste : l'appareil, la formation. C'est le dernier maillon qui manque."]],
    Q18: [["P", "Qu'ils pensent à la saison des pluies. Une solution pour les références quand la route est coupée. Et qu'on travaille avec les guérisseurs plutôt que contre eux : s'ils savaient reconnaître une femme en danger et l'envoyer, beaucoup de choses changeraient."]],
    Q19: [["P", "Non. Et dans mon centre, ce n'est même pas une question de personnes : c'est la pluie qui décide. En saison sèche, une femme a son dépistage et sa référence ; en saison des pluies, la même femme n'a rien. La météo ne devrait pas décider de la santé d'une femme enceinte."]],
    Q20: [["P", "Oui : parlez des guérisseurs, mais sans mépris. Ils sont là, les femmes leur font confiance, et c'est une ressource si on sait la prendre. Si votre étude les présente comme un obstacle, elle passera à côté."]],
  },
};
