// DONNÉES SIMULÉES — P05 et P06 (CS11, rural périphérique ; tensiomètre
// électronique en panne, aucune bandelette de glycémie depuis ~4 mois).
// Ce binôme porte l'essentiel de la triangulation : les deux participants du
// même centre décrivent différemment la même situation matérielle.

export const P05 = {
  journal: "Entretien en kinyarwanda, dans le bureau du titulaire. Participant courtois, sûr de lui, parle du centre au « nous » institutionnel. Registre de présentation marqué : les réponses valorisent l'organisation du service, y compris là où l'observation de la veille montrait autre chose. Je n'ai pas relevé la contradiction pendant l'entretien — ce n'est pas le rôle de l'entretien et cela aurait rompu la relation. Deux interruptions (personnel). À noter : ma visite d'observation ayant précédé l'entretien, le participant savait que j'avais vu la salle ; cela a pu produire l'effet inverse de celui escompté et renforcer le registre défensif. Pour les entretiens suivants, envisager d'inverser l'ordre.",
  reponses: {
    O1: [["P", "Je suis infirmier A2, j'ai plus de vingt-cinq ans de service. J'ai commencé comme aide, puis la formation, puis j'ai été affecté dans plusieurs centres. Ici je suis titulaire depuis huit ans. Je fais la CPN aussi, parce qu'un titulaire dans un petit centre fait tout : la consultation, les rapports, les commandes, les réunions avec le secteur."]],
    O2: [["P", "Nous commençons à sept heures. Les femmes viennent, nous les recevons dans l'ordre d'arrivée. Nous sommes deux pour la CPN. Nous faisons tout ce qui est prévu : les constantes, l'examen, les médicaments, les conseils. Vers midi nous terminons. C'est un centre organisé, nous n'avons pas de problème de désordre."]],
    Q1: [["P", "La femme arrive, on l'inscrit dans le registre, on prend son poids et sa tension, on l'examine, on lui donne ce qui est prescrit, et on lui donne son rendez-vous. C'est la procédure et nous la suivons."]],
    Q2: [["P", "La tension se prend au début, avec les constantes. Nous la prenons systématiquement, à toutes les femmes. C'est obligatoire dans la CPN et nous ne sautons pas cette étape."], ["E", "Pouvez-vous me donner un exemple ?"], ["P", "Tous les jours. Chaque femme qui entre ici a sa tension prise et inscrite. Pour le sucre, c'est autre chose : nous n'avons pas de glucomètre. Ça, c'est un manque du niveau supérieur, ce n'est pas nous."]],
    Q3: [["P", "Il y a eu un cas l'année dernière. Une femme, je crois la troisième grossesse, tension très élevée, dans les 170. Nous l'avons référée à Kibungo le jour même. Elle a été prise en charge là-bas. C'est la procédure : on trouve, on réfère."], ["E", "Comment cela s'est-il passé exactement ?"], ["P", "Comme je vous dis : on a mesuré, on a confirmé, on a écrit, elle est partie. Il n'y a pas eu de difficulté particulière."], ["E", "Et ensuite ?"], ["P", "Ensuite elle est revenue une fois, puis elle a accouché. Je crois que tout s'est bien passé. (silence) Je n'ai pas le détail."]],
    Q4: [["P", "Je lui ai expliqué que la tension élevée est dangereuse pour la grossesse et qu'il faut aller à l'hôpital. Nous expliquons toujours. Une femme qui part sans comprendre ne part pas."]],
    Q5: [["P", "Certaines comprennent, d'autres non. Celles qui ont fait l'école comprennent. Les autres, il faut répéter. Le problème n'est pas l'explication, c'est qu'elles oublient ou qu'elles n'appliquent pas."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Qu'il faut suivre les conseils qu'on lui donne. Nous, nous faisons notre travail ; après, c'est à elle de faire le sien."]],
    Q6: [["P", "J'explique de la même manière à toutes. C'est le même message pour tout le monde, il n'y a pas de différence — nous ne faisons pas de différence entre les patientes ici."], ["E", "Vous avez employé le mot « différence », qu'entendez-vous par là ?"], ["P", "Je veux dire que nous ne privilégions personne. Maintenant, si la personne ne comprend pas, je vais répéter plus lentement. Avec une femme âgée qui n'a pas été à l'école, on parle plus simplement, c'est normal. Mais le message est le même."]],
    Q7: [["P", "C'est une partie du travail comme les autres. Nous avons beaucoup de choses à faire dans une CPN : la tension en fait partie. Je ne la mets pas au-dessus ni en dessous."]],
    Q8: [["P", "Oui. C'est dans les directives de la CPN. Nous appliquons les directives."]],
    Q9: [["P", "L'expérience. Après vingt-cinq ans, on sait reconnaître une femme qui ne va pas bien avant même de mesurer. Et l'organisation du centre : chacun sait ce qu'il fait."]],
    Q10: [["P", "(silence) Il y a la question des bandelettes de sucre : nous n'en avons pas reçu depuis plusieurs mois, peut-être quatre. Donc le sucre, nous ne pouvons pas. Pour la tension, nous avons l'appareil."], ["E", "Pouvez-vous m'en dire davantage sur l'appareil ?"], ["P", "Nous avons un appareil électronique et un manuel. L'électronique donne des erreurs depuis quelque temps, il faudrait le faire réparer. Alors nous utilisons le manuel. Ce n'est pas un problème, le manuel est même plus fiable — c'est ce qu'on nous a appris."], ["E", "Et le manuel, est-il toujours disponible ?"], ["P", "Il est au centre. Parfois le curatif l'utilise. Alors on attend un moment. Mais on finit toujours par mesurer."]],
    Q11: [["P", "Les femmes sont différentes, oui, mais pas dans le service qu'elles reçoivent. La différence est chez elles : il y a celles qui suivent les conseils et celles qui ne les suivent pas. Il y a celles qui viennent à l'heure et celles qui viennent quand elles veulent."]],
    Q12: [["P", "Celles qui ne comprennent pas l'importance de la CPN. Il y a encore des femmes qui pensent que la grossesse n'est pas une maladie et qu'il n'y a pas besoin de venir. Avec celles-là, c'est difficile, parce qu'on leur explique et elles ne reviennent pas."], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "L'expérience. On voit les mêmes familles. Il y a des ménages où on ne vient jamais, et d'autres où on vient pour tout. Ce n'est pas une question d'argent seulement, c'est une question de mentalité."]],
    Q13: [["P", "On confirme, on écrit sur le carnet et on envoie à l'hôpital. Le rôle du centre de santé s'arrête à la référence : après, c'est l'hôpital. Nous n'avons pas de retour écrit, mais nous connaissons les gens, on finit par savoir."]],
    Q14: [["P", "Parce qu'elles ne comprennent pas l'importance. Il y a aussi la distance, c'est vrai, et les travaux. Mais beaucoup, c'est la mentalité : on attend que le ventre soit gros. On fait de la sensibilisation avec les agents de santé communautaire, mais ça prend du temps de changer les habitudes."]],
    Q15: [["P", "Moi je n'ai pas eu de formation sur ces maladies, non. J'ai l'expérience. Pour la tension, on n'a pas besoin de formation, c'est le métier de base. Pour le diabète de la grossesse, je reconnais que je ne connais pas bien ; mais comme nous n'avons pas l'appareil, la question ne se pose pas."]],
    Q16: [["P", "La supervision regarde nos rapports. Ils veulent les chiffres à temps et les registres remplis. Ils ne posent pas de question sur la tension en particulier. Quand tout est en ordre, ils sont satisfaits."]],
    Q17: [["P", "Le glucomètre et les bandelettes. Parce que c'est la seule chose qui manque complètement. Le reste, nous l'avons et nous le faisons."]],
    Q18: [["P", "Qu'ils envoient le matériel et qu'ils pensent à la maintenance. Un appareil en panne, ici, personne ne vient le réparer. On le met de côté et on attend."]],
    Q19: [["P", "(silence) Bon. Ce n'est pas normal dans l'absolu. Mais c'est la vie du village. Nous travaillons avec ce que nous avons, et je crois que nous faisons correctement notre travail. Ce qui n'est pas normal, c'est que le matériel n'arrive pas."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "Du niveau supérieur, principalement. Et un peu des femmes elles-mêmes, pour ce qui est de venir et de revenir. Nous, ici, nous faisons notre part."]],
    Q20: [["P", "Ajoutez que les centres éloignés reçoivent moins et plus tard. Quand vous écrirez, dites que le centre de santé de la colline n'est pas le centre de santé de la ville, même si les directives sont les mêmes pour les deux."]],
  },
};

export const P06 = {
  journal: "Entretien en kinyarwanda, dans la salle d'accouchement, seul espace fermé disponible. Participante jeune, formée récemment, très volubile sur l'écart entre ce qu'elle a appris et ce qu'elle peut faire. Évoque spontanément le tensiomètre en panne, sujet que son collègue titulaire avait présenté autrement le même jour ; je n'ai pas fait état de l'autre entretien. Ton indigné, jamais accusateur envers une personne. Une longue pause après Q19, puis reprise. Réflexion : la confidentialité entre participants du même centre est ici un enjeu réel, deux personnes seulement assurant la CPN. Le code de structure ne protège pas d'une identification interne ; ne citer aucun extrait qui associerait ancienneté et propos critiques sur l'équipement.",
  reponses: {
    O1: [["P", "J'ai fini l'école de sage-femme A1 il y a deux ans, et j'ai été affectée ici directement. La CPN, je la fais depuis un peu plus d'un an. L'année dernière j'ai eu une formation de trois jours sur les maladies non transmissibles, à Kibungo — j'étais la seule du centre à y aller."]],
    O2: [["P", "Nous sommes deux. Il y a la CPN, les accouchements, et le reste. Trente femmes environ le matin. Ce que je peux dire, c'est que la journée dépend du matériel : il y a des matins où tout va, et des matins où on cherche le tensiomètre pendant une demi-heure."]],
    Q1: [["P", "Inscription, poids, tension si possible, attente, examen, médicaments, rendez-vous."], ["E", "Vous avez dit « si possible », qu'entendez-vous par là ?"], ["P", "Parce que l'appareil électronique ne marche plus. Il affiche une erreur, on ne peut plus l'utiliser. Il reste sur la table mais il ne sert à rien. Il y a un tensiomètre manuel, mais il est partagé avec le curatif, donc parfois il n'est pas là. Quand il n'est pas là, la femme passe sans qu'on prenne sa tension. Ça arrive plusieurs fois par semaine."]],
    Q2: [["P", "Normalement la tension est au début, avec les constantes. Dans les faits, elle est prise quand l'appareil est disponible. Le sucre, il n'y a pas d'appareil du tout, et pas de bandelettes depuis que je suis ici — enfin, depuis plusieurs mois. À la formation on m'a expliqué comment dépister le diabète gestationnel, les critères, quand faire la glycémie. Je sais le faire. Je ne l'ai jamais fait ici."], ["E", "Qu'est-ce que cela vous fait ?"], ["P", "(silence) C'est frustrant. J'ai la connaissance et je n'ai pas l'outil. C'est comme apprendre à conduire et ne pas avoir de voiture. Et avec le temps j'ai peur d'oublier."]],
    Q3: [["P", "Oui, il y a deux mois. Une femme, deuxième grossesse, environ trente-deux semaines. J'ai pris sa tension avec le manuel : 160 sur 100. J'ai attendu, j'ai reprise : 155 sur 98. J'ai fait la bandelette urinaire, il restait quelques bandelettes, il y avait une croix de protéines."], ["E", "Que s'est-il passé ?"], ["P", "Je suis allée voir le titulaire, on a décidé de la référer. Je lui ai expliqué longuement, parce que je venais de la formation et que j'avais les mots. Elle est partie le lendemain, pas le jour même, parce qu'il fallait organiser. À l'hôpital on l'a gardée. Elle a accouché là-bas, un peu avant terme, mais l'enfant va bien. Celle-là je la connais, je la croise au marché."], ["E", "Et ensuite ?"], ["P", "Après l'accouchement, plus rien. Personne ne suit sa tension maintenant. Elle m'a demandé une fois si elle devait continuer quelque chose, et je n'ai pas su quoi lui dire, parce qu'il n'y a pas de service pour ça ici."]],
    Q4: [["P", "Je lui ai expliqué que la tension trop forte peut abîmer le placenta et faire que le bébé ne grandit pas bien, et que pour elle ça peut donner des crises [kugagara]. Je lui ai dit les signes d'alerte : mal à la tête qui ne passe pas, vue trouble, gonflement du visage et des mains, douleur en haut du ventre. Et je lui ai dit que ce n'était pas sa faute, parce que beaucoup pensent qu'elles ont fait quelque chose de mal."]],
    Q5: [["P", "Ça dépend de comment on le dit. Si je prends le temps, elles comprennent le danger et les signes. Ce qu'elles ne comprennent pas, c'est l'après : que ça peut rester après l'accouchement. Ça, même moi j'ai appris ça seulement à la formation."], ["E", "Et qu'aimeriez-vous qu'elle comprenne ?"], ["P", "Que la tension n'est pas une maladie de la grossesse seulement. Que c'est une maladie de sa vie, et qu'il faut la surveiller après."]],
    Q6: [["P", "Oui, j'adapte, mais j'essaie que ce soit sur la forme et pas sur le contenu. Avec une femme qui n'a pas été à l'école, j'utilise des images avec les mains, je fais répéter, je demande « redis-moi ce que tu as compris ». Ça prend plus de temps, mais elle reçoit la même chose."], ["E", "Pouvez-vous me donner un exemple ?"], ["P", "Pour expliquer la tension, je dis : le sang pousse dans le corps comme l'eau dans un tuyau ; si ça pousse trop, le tuyau souffre. Avec les mains. Et après je demande de me le redire. Quand elle me le redit mal, je recommence. Le problème c'est que les jours où il y a beaucoup de monde, je ne peux pas faire ça, et ces jours-là je dis juste « va à l'hôpital »."]],
    Q7: [["P", "Pour moi c'est important, peut-être plus que pour d'autres parce que j'ai eu la formation. Mais dans la pratique, je fais ce que le matériel permet. Si je compare aux autres tâches : l'anémie et le paludisme, je peux les traiter ici, donc je m'en occupe. La tension, je peux seulement la trouver et l'envoyer ailleurs. Le sucre, je ne peux même pas le trouver. Plus on est impuissant, moins on y pense — et ça, c'est grave."]],
    Q8: [["P", "Oui, complètement. C'est même une des choses qui justifient la CPN au-delà de la grossesse : on voit une femme jeune plusieurs fois, on peut trouver une maladie qu'elle aurait sinon découverte à cinquante ans. Mais alors il faut nous donner les moyens de le faire, sinon c'est écrit dans les directives et c'est faux dans la réalité."]],
    Q9: [["P", "La formation, d'abord : je sais quoi chercher et comment le dire. Et quand le tensiomètre manuel est là et que nous sommes deux, ça se passe bien. Ces jours-là je fais mon travail comme je voudrais."]],
    Q10: [["P", "La semaine dernière. Le manuel était au curatif, l'électronique en panne. J'avais douze femmes. Je n'ai pris aucune tension pendant presque une heure. Après j'ai récupéré l'appareil et j'ai rappelé celles qui étaient encore là — quatre étaient déjà parties. Donc quatre femmes ce matin-là sont venues en CPN et sont rentrées sans qu'on ait mesuré leur tension."], ["E", "Comment l'expliquez-vous ?"], ["P", "Un appareil en panne que personne ne répare, et un seul appareil de secours pour tout le centre. Ce n'est pas plus compliqué que ça. On a signalé, on a écrit, on attend."]],
    Q11: [["P", "Oui. Et je vais dire une chose : la différence ne vient pas des femmes, elle vient de l'heure et du matériel. La femme qui arrive quand le tensiomètre est là a un dépistage ; celle qui arrive quand il est de l'autre côté n'en a pas. Elles n'ont rien fait de différent."]],
    Q12: [["P", "Celles qui viennent de loin, parce que si je trouve quelque chose, aller à Kibungo est un problème d'argent et de temps. Et celles qui sont accompagnées par quelqu'un qui décide pour elles : j'explique à la femme, et c'est la belle-mère ou le mari qui décide si on part ou pas. Alors je dois convaincre deux personnes."]],
    Q13: [["P", "Je reprends après repos, je fais la bandelette urinaire s'il en reste, j'en parle au titulaire, et on réfère. J'écris sur le carnet, il n'y a pas de fiche. Mon rôle s'arrête là, et c'est ça qui me gêne : je ne sais pas ce que devient la femme. Celle dont je vous ai parlé, je le sais par hasard, parce que je l'ai croisée."]],
    Q14: [["P", "La distance, l'argent, la charge de travail à la maison. Et aussi — je l'ai remarqué — celles qui sont venues une fois et qui ont attendu trois heures pour rien, parce qu'il manquait quelque chose, celles-là ne reviennent pas volontiers. Nous perdons des femmes par nos propres ruptures."]],
    Q15: [["P", "Le centre ne m'a pas préparée : c'est le district, avec la formation de l'année dernière. Et je suis la seule à l'avoir eue, ce qui fait que quand je ne suis pas là, personne ne fait ce que j'ai appris. J'ai proposé d'expliquer aux collègues, on n'a pas trouvé le temps."]],
    Q16: [["P", "Je pense que pour eux c'est secondaire. Ce qu'on nous demande, ce sont les chiffres de la CPN1, de la CPN4, de la vaccination. Personne n'est jamais venu demander combien de femmes ont eu leur tension prise. S'ils le demandaient, on trouverait le moyen de le faire — c'est comme ça que ça marche."]],
    Q17: [["P", "Un tensiomètre qui marche, à nous, qui ne sorte pas de la salle de CPN. Pourquoi celui-là plutôt que le glucomètre ? Parce que la tension, c'est ce qui tue ici, et parce que nous sommes à un appareil près de faire correctement la moitié du travail. Le glucomètre viendra après."]],
    Q18: [["P", "Qu'ils prévoient la réparation, pas seulement l'achat. Et qu'ils forment tout le monde, pas une personne par centre — parce qu'une personne formée qui part en congé, c'est un centre qui redevient comme avant."]],
    Q19: [["P", "(long silence) Non. Ce n'est pas normal, et je ne vais pas dire le contraire. Deux femmes du même village, le même matin : celle qui arrive à huit heures a sa tension, celle qui arrive à neuf heures ne l'a pas parce que l'appareil est parti. Comment est-ce que ce serait normal ?"], ["E", "Qu'est-ce qui vous fait dire cela ?"], ["P", "Parce que ce n'est pas une différence entre les femmes, c'est une différence dans ce que nous, nous donnons. Elles n'y sont pour rien. Quand la différence vient de nous, on ne peut pas l'appeler normale."], ["E", "Selon vous, cela dépend de quoi ?"], ["P", "Du matériel, du nombre de personnes, et de qui a été formé. Trois choses qui se décident ailleurs. Mais une fois qu'on le sait, continuer sans rien dire, ça devient un peu à nous."]],
    Q20: [["P", "Oui. Demandez aussi ce qui se passe après l'accouchement. Nous trouvons des femmes hypertendues, elles accouchent, et elles disparaissent. On dit qu'on fait du dépistage, mais un dépistage qui ne mène à rien, ce n'est pas du dépistage, c'est une mesure."]],
  },
};
