// observations-vague2.mjs — Annexe 2 remplie : onze grilles d'observation.
// DONNÉES SIMULÉES. L'observation porte sur le service, jamais sur les personnes
// ni sur le contenu d'une consultation (annexe 2, § 1 et § 4.2.7 du protocole).
// Les registres ne sont consultés que sous forme agrégée, sans relevé nominatif.

const hygiene = (etat = "savon et solution hydroalcoolique présents") =>
  ({ item: "Consommables d'hygiène", present: "oui", nombre: null, etat, obs: "" });

export const observationsV2 = [
  {
    cs: "CS01", secteur: "urbain", date: "21/09/2026", heures: "07h30 – 12h20",
    A: {
      sallesCpn: 3, echangeNonEntendu: "oui",
      detail: "Deux salles de consultation individuelles fermées et une salle de constantes distincte, avec un paravent devant la table de mesure.",
      femmesRecues: 51, professionnels: 4, posteConstantes: "oui, salle distincte avec un agent affecté",
      dureeMoyenne: "environ 1 h 05",
    },
    S: { frequence: "3 par semaine (lundi, mercredi, vendredi)", observee: "oui", detail: "Séance de 07h30 à 07h55 dans la salle d'attente, animée par une sage-femme, en kinyarwanda, devant environ quarante femmes. Thème du jour : signes de danger pendant la grossesse ; l'affiche sur la tension pendant la grossesse est montrée et commentée (maux de tête, vision floue, œdèmes). Le sucre n'est pas abordé. Une dizaine de femmes arrivent après la fin de la séance.", sujets: "tension : oui (signes de prééclampsie) ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 3, etat: "2 électroniques et 1 manuel, tous fonctionnels", obs: "Brassard grande taille présent — seul centre observé à en disposer." },
      { item: "Glucomètre", present: "oui", nombre: 3, etat: "fonctionnels — 2 au laboratoire, dont un de réserve ; 1 en salle de CPN pour les urgences", obs: "Glycémie de la première CPN demandée par bon pour toutes et faite au laboratoire, juste à côté, le matin même ; résultat reporté au carnet et au registre. Le glucomètre de la CPN n'a servi qu'une fois, pour une femme prise de malaise. Contrôle ultérieur sur facteurs de risque, sans épreuve de charge à 24-28 semaines." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 48, etat: "péremption 04/2027", obs: "Au laboratoire, avec une part pour la CPN. Fiche de stock tenue à jour, seuil de réapprovisionnement inscrit." },
      { item: "Balance", present: "oui", nombre: 2, etat: "fonctionnelles", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "toise fixée au mur", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 90, etat: "péremption 06/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non — aucune rupture signalée sur la période",
    glycemieCpn: "faite", glucoCpn: "oui", glycemieT3: "sur facteurs de risque", rattrapage: "oui",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiché au poste de constantes, en kinyarwanda, avec seuils et conduite à tenir." },
      { item: "Protocole diabète en grossesse", present: "oui", accessible: "oui", obs: "Algorithme affiché à côté du précédent, avec la glycémie de la première CPN pour toutes et les critères pour la refaire entre 24 et 28 semaines." },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Fiche de référence à deux volets ; le second volet (contre-référence) revient parfois rempli de l'hôpital — huit retours classés sur le trimestre." },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Quatre affiches illustrées en kinyarwanda, dont une sur la tension pendant la grossesse ; un dépliant à emporter, en nombre limité." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension artérielle renseignée sur la quasi-totalité des lignes. Case « diabète » renseignée sur toutes les lignes de première CPN consultées sauf deux, qui portent la mention « glycémie à refaire au prochain rendez-vous » ; le test y figure à la visite suivante.",
      tracageReference: "oui — registre de référence et classeur des contre-références",
    },
    E: "Centre le mieux doté des seize observés : le circuit de la glycémie — bon rempli en CPN, test au laboratoire voisin, résultat rapporté le matin même — fonctionne sous les yeux de l'observateur, et une femme non testée est notée pour un rattrapage au rendez-vous suivant. Affluence la plus forte de la série, absorbée par une organisation en trois postes. Un stagiaire est présent au poste de constantes, encadré. Une femme demande un dépliant ; il n'en reste plus en fin de matinée.",
    F: "Ce centre change la lecture de l'ensemble : il montre que le dépistage complet est réalisable dans le district, et non une exigence hors d'atteinte. Mais il le montre dans le secteur le moins pauvre et le plus proche de l'hôpital — la variable équité se lit donc dans la répartition des moyens entre centres, autant que dans les pratiques au sein d'un centre. À ne pas présenter comme un modèle transposable sans dire ce qui le rend possible.",
  },
  {
    cs: "CS04", secteur: "rural périphérique", date: "21/09/2026", heures: "08h15 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "partiellement",
      detail: "Salle fermée, mais la fenêtre donne sur l'attente et reste ouverte pour la ventilation.",
      femmesRecues: 26, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 50",
    },
    S: { frequence: "2 par semaine (mardi, jeudi)", observee: "non — jour sans séance", detail: "Cahier des séances consulté : derniers thèmes inscrits « hygiène » et « nutrition », avec le nombre de femmes présentes. Aucun thème sur la tension ou le sucre depuis trois mois.", sujets: "tension : non (cahier) ; sucre : non (cahier)" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel, fonctionnel", obs: "Stéthoscope usé ; l'équipe signale une difficulté d'auscultation en ambiance bruyante." },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel — au laboratoire ; aucun glucomètre en salle de CPN", obs: "Le seul laborantin est en formation au district le jour de l'observation : les bons de glycémie de la première CPN sont reportés, et la CPN n'a pas d'appareil pour le remplacer." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 10, etat: "péremption 02/2027", obs: "Au laboratoire." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 15, etat: "péremption 03/2027", obs: "" },
      hygiene("savon présent, solution hydroalcoolique absente"),
    ],
    ruptureTroisMois: "oui — bandelettes urinaires, rupture d'environ deux semaines en août 2026",
    glycemieCpn: "absence", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Fiche de référence du district, sans volet de retour." },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Colonne tension renseignée sur environ quatre lignes sur cinq. Case « diabète » de la première CPN renseignée sur une partie des lignes seulement ; vide, selon l'équipe, les jours d'absence du laborantin.",
      tracageReference: "oui — souches conservées",
    },
    E: "Matinée calme. Le titulaire assure à la fois la CPN et les rapports, et s'absente vingt minutes pour une réunion téléphonique avec le district. Le seul laborantin est en formation au district : les femmes de première CPN repartent avec un bon de glycémie qu'aucun service ne peut honorer ce jour-là.",
    F: "Centre « moyen » à tous égards : ni démuni, ni outillé. C'est précisément ce profil, le plus fréquent, qui manquait à la vague 1, construite sur des contrastes. Le test de la première CPN y dépend d'une seule personne, le laborantin : c'est la forme la moins visible de l'interruption, puisque ni l'appareil ni les bandelettes ne manquent. Rien de marquant entre propos et constats.",
  },
  {
    cs: "CS05", secteur: "rural périphérique", date: "22/09/2026", heures: "08h40 – 12h10",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée, attente sous un auvent distant de quelques mètres.",
      femmesRecues: 19, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 30",
    },
    S: { frequence: "2 par semaine (mardi, vendredi)", observee: "oui", detail: "Séance de 08h00 à 08h20 sous l'auvent, animée par la sage-femme, devant une vingtaine de femmes. Thème : prévention de la transmission du VIH de la mère à l'enfant. Boîte à images utilisée.", sujets: "tension : non ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel — au laboratoire ; aucun glucomètre en salle de CPN", obs: "Inutilisable faute de bandelettes valides : aucune glycémie de première CPN n'est faite pendant la demi-journée." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 30, etat: "PÉRIMÉES depuis 05/2026", obs: "Flacons conservés dans l'armoire du laboratoire ; l'équipe dit attendre leur remplacement." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 35, etat: "péremption 02/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie valides absentes depuis mai 2026",
    glycemieCpn: "rupture", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "partiellement", obs: "Rangé dans un classeur sur le bureau." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension renseignée régulièrement. Case « diabète » de la première CPN vide depuis mai 2026 (bandelettes invalides).",
      tracageReference: "oui",
    },
    E: "Affluence la plus faible des centres ruraux observés. L'équipe explique que la route d'accès devient impraticable en saison des pluies et que la fréquentation chute alors fortement. Une femme arrive à pied après, dit-elle, plus de deux heures de marche.",
    F: "Le paradoxe de ce centre — un glucomètre en état de marche et trente bandelettes inutilisables — dit quelque chose du circuit d'approvisionnement que l'inventaire « présent / absent » ne capte pas : l'intrant est là, et il ne sert pas. La grille devrait distinguer « présent » et « utilisable » ; à proposer en révision de l'annexe 2.",
  },
  {
    cs: "CS06", secteur: "urbain", date: "22/09/2026", heures: "07h45 – 12h30",
    A: {
      sallesCpn: 2, echangeNonEntendu: "partiellement",
      detail: "Deux salles, dont une sert aussi au planning familial ; les constantes sont prises dans un couloir semi-ouvert.",
      femmesRecues: 44, professionnels: 3, posteConstantes: "oui, tenu ce jour-là par un stagiaire",
      dureeMoyenne: "environ 1 h 35",
    },
    S: { frequence: "3 par semaine", observee: "oui", detail: "Séance de 07h50 à 08h15 dans la salle d'attente, animée par une infirmière ; thème : allaitement maternel exclusif. Deux pères présents. La séance est interrompue une fois pour un accouchement.", sujets: "tension : non ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "1 électronique fonctionnel ; 1 électronique en panne", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 2, etat: "fonctionnels — 1 au laboratoire ; 1 au poste de constantes pour les urgences", obs: "Glycémie de la première CPN demandée par bon pour toutes et faite au laboratoire pendant la demi-journée ; ensuite sur facteurs de risque seulement. Le glucomètre de la CPN est utilisé par la professionnelle formée ; le stagiaire ne s'en sert pas." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 5, etat: "péremption 12/2026", obs: "Au laboratoire. Stock très faible." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "toise", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 50, etat: "péremption 04/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie en quantité insuffisante, réapprovisionnement partiel",
    glycemieCpn: "faite", glucoCpn: "oui", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiché, en anglais." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "partiellement", obs: "Une affiche sur la nutrition, en kinyarwanda." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension renseignée régulièrement ; écritures de plusieurs mains différentes sur une même semaine. Case « diabète » de la première CPN renseignée, sauf pendant les semaines de rupture des bandelettes.",
      tracageReference: "oui",
    },
    E: "Centre situé sur l'axe routier, affluence forte. L'équipe indique que deux professionnels ont été réaffectés dans l'année ; la participante interrogée est arrivée il y a moins de deux ans. Le stagiaire au poste de constantes annonce les valeurs à voix haute.",
    F: "La multiplicité des écritures dans le registre et la présence d'un stagiaire aux constantes rendent visible un facteur que la vague 1 n'avait pas fait apparaître : la rotation du personnel. Elle dilue les consignes et interrompt la transmission des pratiques — à rapprocher du code « transmission informelle entre collègues ».",
  },
  {
    cs: "CS08", secteur: "rural périphérique", date: "23/09/2026", heures: "08h00 – 11h50",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée ; l'attente se fait dans une pièce distincte.",
      femmesRecues: 28, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 40",
    },
    S: { frequence: "2 par semaine", observee: "non — jour sans séance", detail: "Cahier des séances présent mais non rempli depuis cinq semaines ; l'équipe explique l'absence par le départ d'une infirmière.", sujets: "non documenté" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "NON fonctionnel — au laboratoire, message d'erreur persistant ; aucun glucomètre en salle de CPN", obs: "Panne signalée selon l'équipe ; aucune glycémie de première CPN n'est faite pendant la demi-journée ; les femmes à risque sont orientées vers l'hôpital de district." },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "Sans objet tant que l'appareil est en panne." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 22, etat: "péremption 05/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non renseigné",
    glycemieCpn: "panne", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Une affiche FAITE À LA MAIN par l'équipe, en kinyarwanda, sur les signes de danger de la grossesse, dont « maux de tête forts » et « gonflement du visage ». Dessins simples, lisible pour une personne peu alphabétisée." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension renseignée régulièrement. Case « diabète » de la première CPN vide depuis la panne du glucomètre.",
      tracageReference: "oui",
    },
    E: "Deux animatrices de santé maternelle (ASM) passent dans la matinée : l'une apporte la liste des femmes enceintes repérées dans son village, l'autre raccompagne une femme orientée la semaine précédente. L'équipe et les ASM se connaissent par leur nom.",
    F: "L'affiche faite à la main est l'élément le plus instructif de la journée : elle montre une réponse locale à l'absence de supports fournis, et elle est plus lisible que les affiches imprimées vues ailleurs. Le lien avec les animatrices de santé maternelle (ASM) ouvre une piste absente du cadre conceptuel : le relais communautaire comme prolongement du dépistage.",
  },
  {
    cs: "CS09", secteur: "rural périphérique", date: "23/09/2026", heures: "08h30 – 11h30",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Bâtiment récent ; salle fermée, carrelée, bien éclairée.",
      femmesRecues: 14, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 10",
    },
    S: { frequence: "annoncées 2 par semaine, irrégulières", observee: "non", detail: "Pas de cahier des séances. Le titulaire indique que les séances sont suspendues les semaines où il est seul au centre.", sujets: "non documenté" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique NEUF, fonctionnel", obs: "Reçu à l'ouverture du centre." },
      { item: "Glucomètre", present: "oui", nombre: 2, etat: "fonctionnels — 1 au laboratoire ; 1 NEUF en salle de CPN pour les urgences, livré avec le kit de CPN", obs: "Glycémie de la première CPN demandée par bon pour toutes et faite au laboratoire pendant la demi-journée ; ensuite sur facteurs de risque seulement." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 25, etat: "péremption 06/2027", obs: "Au laboratoire." },
      { item: "Balance", present: "oui", nombre: 1, etat: "neuve", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "non", nombre: 0, etat: "—", obs: "Non encore livrées." },
      hygiene(),
    ],
    ruptureTroisMois: "non pour la glycémie — dotation initiale incomplète pour d'autres intrants (bandelettes urinaires, registre), non une rupture",
    glycemieCpn: "faite", glucoCpn: "oui", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "non", accessible: "—", obs: "Orientation écrite sur le carnet." },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "partiellement", accessible: "oui", obs: "Le registre standard n'est pas encore livré : un cahier quadrillé en tient lieu, avec des colonnes tracées à la règle." },
    ],
    D: {
      rubriqueTa: "oui (colonne tracée à la main)", rubriqueGlycemie: "oui (colonne tracée à la main)",
      renseignement: "Colonnes tension et glycémie présentes dans le cahier, tracées à la main, et renseignées ; la tenue dépend entièrement de l'équipe, sans modèle imposé.",
      tracageReference: "non",
    },
    E: "Ancien poste de santé récemment érigé en centre de santé. Le bâtiment et l'équipement de base sont neufs ; les supports, les intrants et la dotation complète ne suivent pas encore. Faible fréquentation, que l'équipe attribue au fait que la population continue de se rendre à l'ancien centre de rattachement.",
    F: "Ce centre montre une forme d'inégalité qui n'est ni une rupture ni une panne : une dotation incomplète (bandelettes urinaires, registre standard). La glycémie de la première CPN y suit le circuit des autres centres : bon de la CPN, test au laboratoire. Il interroge le calendrier de mise en service plus que la gestion courante — élément non anticipé par la grille.",
  },
  {
    cs: "CS10", secteur: "rural périphérique", date: "24/09/2026", heures: "07h50 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "partiellement",
      detail: "Salle fermée, mais un passage vers la pharmacie la traverse.",
      femmesRecues: 33, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 2 h",
    },
    S: { frequence: "2 par semaine (mardi, vendredi)", observee: "non — jour sans séance", detail: "Cahier des séances consulté : le mardi précédent, thème « signes de danger », boîte à images mentionnée. La boîte à images présente au centre comporte une planche sur les maux de tête et les œdèmes, aucune sur le diabète.", sujets: "tension : oui (cahier et boîte à images) ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel — au laboratoire ; aucun glucomètre en salle de CPN", obs: "Glycémie de la première CPN demandée par bon pour toutes et faite au laboratoire, puis sur facteurs de risque. En urgence, la CPN appelle le laborantin, qui vient faire le test dans la salle. Une femme arrivée un jour de rupture est notée pour un test au rendez-vous suivant." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 14, etat: "péremption 01/2027", obs: "Au laboratoire." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 30, etat: "péremption 03/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non",
    glycemieCpn: "faite", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "oui",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiché." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension renseignée. Case « diabète » de la première CPN renseignée. Une proportion notable de lignes ne comporte qu'une seule visite, sans suite.",
      tracageReference: "oui",
    },
    E: "Population décrite par l'équipe comme mobile : travailleuses agricoles saisonnières, femmes de passage venant d'autres secteurs ou d'autres districts. Plusieurs femmes présentent un carnet ouvert ailleurs. Le registre comporte de nombreuses premières visites sans visite suivante.",
    F: "La mobilité des femmes pose une question que le cadre conceptuel ne traite pas : le dépistage suppose une continuité de suivi que la trajectoire même de certaines femmes rend impossible. Les lignes sans suite du registre ne sont pas des « perdues de vue » au sens habituel : elles ont pu être suivies ailleurs. À ne pas interpréter comme un défaut du service.",
  },
  {
    cs: "CS12", secteur: "rural périphérique", date: "24/09/2026", heures: "08h00 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée, attente extérieure à distance.",
      femmesRecues: 25, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 45",
    },
    S: { frequence: "2 par semaine (lundi, jeudi)", observee: "oui", detail: "Séance de 07h55 à 08h15, animée par un infirmier, devant une vingtaine de femmes. Thème : mutuelle de santé et préparation de l'accouchement ; rappel des documents à apporter.", sujets: "tension : non ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel — au laboratoire ; aucun glucomètre en salle de CPN", obs: "Glycémie de la première CPN de nouveau faite au laboratoire pour toutes depuis le réapprovisionnement, la semaine précédant l'observation." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 20, etat: "péremption 03/2027", obs: "Au laboratoire. Reçues la semaine précédant l'observation, après environ deux mois de rupture." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 18, etat: "péremption 02/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie, environ deux mois (fin juillet à mi-septembre 2026)",
    glycemieCpn: "faite", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "" },
      { item: "Protocole diabète en grossesse", present: "oui", accessible: "partiellement", obs: "Photocopie dans un classeur." },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension renseignée régulièrement. Case « diabète » de la première CPN renseignée jusqu'à fin juillet, vide pendant la rupture, de nouveau renseignée depuis une semaine ; aucune mention de rattrapage pour les femmes reçues pendant la rupture.",
      tracageReference: "oui",
    },
    E: "Organisation stable, équipe ancienne. La colonne glycémie du registre montre nettement la date de la rupture : renseignée régulièrement jusqu'à fin juillet, vide pendant deux mois, de nouveau renseignée depuis le réapprovisionnement.",
    F: "Le registre est ici un instrument de mesure inattendu : la date de rupture s'y lit sans qu'il soit besoin de la demander. Les registres pourraient servir, dans l'étude réelle, à documenter les ruptures plus sûrement que la mémoire des équipes — sous réserve de rester sur des données agrégées.",
  },
  {
    cs: "CS13", secteur: "rural périphérique", date: "25/09/2026", heures: "07h40 – 12h30",
    A: {
      sallesCpn: 2, echangeNonEntendu: "partiellement",
      detail: "Deux salles, portes souvent ouvertes en raison de l'affluence.",
      femmesRecues: 46, professionnels: 3, posteConstantes: "non — constantes prises en salle",
      dureeMoyenne: "environ 2 h 20",
    },
    S: { frequence: "3 par semaine", observee: "oui", detail: "Séance de 07h40 à 08h00, animée par une sage-femme, devant une trentaine de femmes. Thème : signes de danger ; maux de tête et œdèmes cités. Cahier des séances tenu à jour.", sujets: "tension : oui (signes de danger) ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "1 électronique fonctionnel ; 1 manuel fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel — au laboratoire ; aucun glucomètre en salle de CPN", obs: "Glycémie de la première CPN demandée par bon pour toutes et faite au laboratoire ; ensuite sur facteurs de risque seulement. Aucune glycémie de contrôle systématique au troisième trimestre." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 9, etat: "péremption 11/2026", obs: "Au laboratoire." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 40, etat: "péremption 04/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non",
    glycemieCpn: "faite", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Une affiche sur les signes de danger." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Colonne tension renseignée sur la TOTALITÉ des lignes consultées. Sur les pages examinées, une part très élevée des valeurs inscrites est identique (« 120/80 » ou « 110/70 »), dans une proportion supérieure à celle observée dans les autres centres. Case « diabète » de la première CPN renseignée.",
      tracageReference: "oui",
    },
    E: "Affluence parmi les plus fortes de la série, dans un centre rural. Trois professionnels pour quarante-six femmes. Pendant la période d'observation, plusieurs femmes sortent de la salle en moins de cinq minutes.",
    F: "La concentration de valeurs identiques dans un registre intégralement rempli ne prouve rien par elle-même et ne doit être imputée à personne : elle peut refléter des valeurs réellement fréquentes, une habitude d'arrondi, ou une inscription faite sans mesure sous la pression de l'affluence. Elle invite en revanche à ne pas lire un registre complet comme la preuve d'un dépistage réalisé. À confronter aux propos de la participante de ce centre, qui aborde elle-même le sujet.",
  },
  {
    cs: "CS15", secteur: "rural périphérique", date: "28/09/2026", heures: "08h20 – 11h45",
    A: {
      sallesCpn: 1, echangeNonEntendu: "non",
      detail: "Salle unique dont la porte ne ferme plus ; l'attente est dans le couloir attenant.",
      femmesRecues: 22, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 50",
    },
    S: { frequence: "2 par semaine (lundi, jeudi)", observee: "oui", detail: "Séance de 08h20 à 08h40, animée par un infirmier, devant dix-sept femmes. Thème : signes de danger ; « la tête qui fait très mal » est citée. Pas de support visuel.", sujets: "tension : oui (un signe cité) ; sucre : non" },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel ancien, poire réparée au ruban adhésif", obs: "Fonctionne, mais la lecture demande plusieurs tentatives." },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel — au laboratoire ; aucun glucomètre en salle de CPN", obs: "Glycémie de la première CPN demandée par bon pour toutes et faite au laboratoire le matin ; le laboratoire ne prélève plus après 12 heures : deux femmes reçues en fin de matinée repartent avec leur bon, sans prélèvement." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 8, etat: "péremption 12/2026", obs: "Au laboratoire ; la consultation MNT puise dans le même stock." },
      { item: "Balance", present: "oui", nombre: 1, etat: "mécanique, à étalonner", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 10, etat: "péremption 12/2026", obs: "" },
      hygiene("savon présent, eau au bidon"),
    ],
    ruptureTroisMois: "oui — bandelettes urinaires intermittentes",
    glycemieCpn: "faite", glucoCpn: "non", glycemieT3: "sur facteurs de risque", rattrapage: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Colonne tension renseignée sur environ deux lignes sur trois. Case « diabète » de la première CPN renseignée sur la plupart des lignes ; vide surtout pour les femmes reçues en fin de matinée.",
      tracageReference: "oui",
    },
    E: "Équipement le plus vétuste de la série après CS11. Le tensiomètre réparé fonctionne mais allonge chaque mesure. Ambiance calme, rapports cordiaux.",
    F: "La porte qui ne ferme pas résume l'absence d'espace confidentiel mieux que toute catégorie de la grille. Rien de marquant entre propos et constats ; le participant décrit lui-même l'appareil réparé.",
  },
];
