// observations.mjs — Annexe 2 remplie : cinq grilles d'observation du service.
// DONNÉES SIMULÉES. L'observation porte sur le service, jamais sur les personnes
// ni sur le contenu d'une consultation (annexe 2, § 1 et § 4.2.7 du protocole).

export const observations = [
  {
    cs: "CS02", secteur: "urbain", date: "07/09/2026", heures: "07h40 – 12h15",
    A: {
      sallesCpn: 2,
      echangeNonEntendu: "partiellement",
      detail: "La salle de consultation ferme, mais la prise des constantes se fait dans le couloir d'attente, où les valeurs sont annoncées à voix audible.",
      femmesRecues: 38, professionnels: 3, posteConstantes: "oui, table dédiée dans le couloir",
      dureeMoyenne: "environ 1 h 40 entre entrée et sortie (estimation de flux, sans suivi individuel)",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "1 électronique fonctionnel ; 1 manuel dont la poire fuit", obs: "Brassard grande taille absent ; un seul brassard adulte standard pour les deux appareils." },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel (test de contrôle effectué par l'équipe le matin)", obs: "Non utilisé pendant la demi-journée." },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "Dernier flacon périmé en mars 2026, conservé dans le tiroir." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 40, etat: "péremption 08/2027", obs: "Utilisées systématiquement (protéinurie)." },
      { item: "Consommables d'hygiène", present: "oui", nombre: null, etat: "savon et solution hydroalcoolique présents", obs: "" },
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie, rupture continue signalée par l'équipe",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiche plastifiée au mur, en anglais, datée 2021." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "Aucun document propre au diabète gestationnel." },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Carnet de référence à souches vers l'hôpital de district." },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "partiellement", obs: "Deux affiches en kinyarwanda sur l'alimentation de la femme enceinte ; aucune sur l'HTA ou le diabète. Texte dense, peu d'illustrations : lisibilité faible pour une personne peu alphabétisée." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "La colonne tension artérielle est renseignée sur la quasi-totalité des lignes consultées. Aucune colonne glycémie dans le registre en usage.",
      tracageReference: "oui — souches du carnet de référence conservées, 4 références pour tension élevée sur le mois en cours",
    },
    E: "Affluence forte dès 07h30 ; file d'attente extérieure sous auvent. Deux interruptions pour une urgence obstétricale, la consultation prénatale suspendue environ vingt-cinq minutes. Le personnel s'organise sans consigne écrite visible : la répartition des tâches se règle oralement. Une professionnelle annonce à voix haute, depuis le couloir, une valeur de tension à une collègue située dans la salle.",
    F: "Je pensais que la contrainte principale serait l'équipement. Ici l'équipement de mesure de la tension existe : ce qui manque, c'est l'espace pour dire un résultat sans qu'il soit entendu, et les bandelettes de glycémie. Contraste avec les entretiens : les deux participants de ce centre décrivent une explication individualisée, que la configuration du couloir rend matériellement difficile à tenir. Ma présence, assise près de l'entrée, a probablement accru le soin apporté au lavage des mains les premières minutes.",
  },
  {
    cs: "CS03", secteur: "urbain", date: "17/08/2026", heures: "08h00 – 12h30",
    A: {
      sallesCpn: 2, echangeNonEntendu: "oui",
      detail: "Une salle de consultation individuelle et une salle de constantes fermée.",
      femmesRecues: 42, professionnels: 4, posteConstantes: "oui, salle distincte",
      dureeMoyenne: "environ 1 h 15",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "2 électroniques fonctionnels", obs: "Brassard grande taille absent ; signalé par l'équipe comme une gêne pour les patientes corpulentes." },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel", obs: "" },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 12, etat: "péremption 11/2026", obs: "Stock faible ; l'équipe déclare les réserver aux femmes présentant des facteurs de risque." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "toise fonctionnelle", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 60, etat: "péremption 02/2027", obs: "" },
      { item: "Consommables d'hygiène", present: "oui", nombre: null, etat: "complets", obs: "" },
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie en rupture pendant environ six semaines (juin-juillet 2026), réapprovisionnement partiel",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiche au poste de constantes, en kinyarwanda, avec seuils de renvoi." },
      { item: "Protocole diabète en grossesse", present: "oui", accessible: "partiellement", obs: "Photocopie d'un algorithme rangée dans un classeur, non affichée." },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Fiche de référence standardisée, avec copie conservée." },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Trois affiches en kinyarwanda, dont une sur les signes de danger de la grossesse mentionnant la tension élevée. Illustrations présentes." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension artérielle renseignée régulièrement. Colonne glycémie présente mais renseignée sur une minorité de lignes.",
      tracageReference: "oui — colonne d'orientation renseignée, 7 références sur le mois en cours dont 5 pour tension élevée",
    },
    E: "Organisation la plus formalisée des cinq centres observés. Un agent affecté aux constantes pendant toute la matinée. Une femme est repassée deux fois au poste de constantes, la première mesure ayant été jugée élevée : la reprise après repos est une pratique visible, non écrite. Affluence soutenue mais file gérée par numéros d'ordre.",
    F: "Ce centre montre qu'une partie de ce que les participants attribuent au manque de moyens relève en réalité de l'organisation : la salle de constantes distincte suffit à rendre possible ce qui est impossible ailleurs. À nuancer : c'est aussi le centre le mieux doté en personnel. Aucun écart marquant entre propos et constats ici, ce qui doit être noté autant que les écarts.",
  },
  {
    cs: "CS07", secteur: "rural périphérique", date: "24/08/2026", heures: "08h20 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "non",
      detail: "Salle unique séparée de l'attente par un rideau en tissu ; les échanges sont audibles depuis le banc d'attente.",
      femmesRecues: 27, professionnels: 2, posteConstantes: "non — constantes prises sur la même table que l'examen",
      dureeMoyenne: "environ 2 h 10, l'essentiel en attente",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel, fonctionnel", obs: "Un seul appareil pour la consultation prénatale et le service curatif ; déplacé entre les deux." },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "Aucun appareil dans le centre. L'équipe indique que les glycémies se font à l'hôpital de district." },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "Sans objet en l'absence d'appareil." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle, mécanique", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 20, etat: "péremption 05/2027", obs: "Stock faible, usage déclaré sélectif." },
      { item: "Consommables d'hygiène", present: "oui", nombre: null, etat: "savon présent, solution hydroalcoolique absente", obs: "" },
    ],
    ruptureTroisMois: "oui — bandelettes urinaires en rupture environ trois semaines en juillet 2026",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "Aucun document affiché ni disponible au poste de travail." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "partiellement", accessible: "oui", obs: "Pas de fiche dédiée ; l'orientation est écrite à la main sur le carnet de la femme." },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "Aucun support visible dans la salle ni dans l'attente." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Colonne tension artérielle présente, renseignée de façon irrégulière : plusieurs lignes vides sur les pages consultées.",
      tracageReference: "non — aucune trace systématique des orientations ; mention manuscrite sur le carnet de la femme uniquement",
    },
    E: "Deux professionnelles assurent seules la matinée, dont une également chargée de la vaccination : elle quitte la salle à plusieurs reprises. Le rideau laisse passer les voix ; une femme baisse la sienne lorsqu'elle répond. Le tensiomètre est emporté vers le service curatif pendant environ quarante minutes, période pendant laquelle les constantes ne sont pas prises.",
    F: "L'absence de tout support d'information écrit change la portée de la question de la capacitation : ce qui n'est pas dit oralement n'est rattrapé par rien. Contraste net avec les entretiens : la jeune sage-femme de ce centre dit n'avoir jamais réalisé de glycémie — le constat matériel explique cette déclaration sans qu'il faille l'attribuer à sa pratique. Ma présence dans une salle unique a certainement pesé ; je me suis placé à l'extérieur du rideau après vingt minutes.",
  },
  {
    cs: "CS11", secteur: "rural périphérique", date: "31/08/2026", heures: "08h00 – 11h45",
    A: {
      sallesCpn: 1, echangeNonEntendu: "non",
      detail: "Salle unique, porte restant ouverte pour la lumière ; l'attente se tient sous un auvent contigu.",
      femmesRecues: 31, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 2 h",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "1 électronique EN PANNE (affichage d'erreur répété) ; 1 manuel emprunté au service curatif", obs: "L'appareil électronique est conservé sur la table, hors d'usage depuis plusieurs semaines selon l'équipe. Le manuel n'est pas toujours disponible." },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "Aucune depuis environ quatre mois selon l'équipe." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban usé", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 8, etat: "péremption 01/2027", obs: "Stock très faible." },
      { item: "Consommables d'hygiène", present: "partiellement", nombre: null, etat: "savon présent, eau au bidon", obs: "" },
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie (environ quatre mois) et bandelettes urinaires (rupture intermittente)",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "non", accessible: "—", obs: "Orientation orale et mention sur le carnet." },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Colonne tension artérielle souvent vide : sur une page de trente lignes consultée, quatorze valeurs manquantes.",
      tracageReference: "non",
    },
    E: "Le centre le plus démuni des cinq. La mesure de la tension dépend de la disponibilité du tensiomètre manuel partagé : pendant l'observation, plusieurs femmes sortent de la salle sans qu'une mesure ait été prise. Ambiance calme, sans tension apparente entre les professionnels et les femmes. Une femme demande spontanément qu'on lui « mesure le bras », ce qui suggère une attente installée.",
    F: "C'est ici que l'écart entre le déclaré et le constaté est le plus net, et il n'est pas à imputer à une intention : l'un des participants de ce centre affirme que la tension est prise systématiquement, tandis que le registre et l'observation montrent des mesures manquantes. Cet écart informe sur la distance entre la norme intériorisée et la condition d'exercice, ce que le protocole demande précisément de consigner sans l'imputer à une intention du participant.",
  },
  {
    cs: "CS14", secteur: "rural périphérique", date: "14/09/2026", heures: "08h10 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "partiellement",
      detail: "Salle fermée, mais l'attente est immédiatement derrière la porte ; les échanges à voix haute sont perceptibles.",
      femmesRecues: 24, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 50",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique fonctionnel", obs: "Brassard unique, taille standard." },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "NON fonctionnel — message d'erreur persistant", obs: "Appareil reçu il y a environ deux ans ; en panne depuis une date que l'équipe ne situe pas précisément." },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 25, etat: "péremption 10/2026", obs: "Péremption proche." },
      { item: "Consommables d'hygiène", present: "oui", nombre: null, etat: "présents", obs: "" },
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie, sans objet faute d'appareil fonctionnel ; bandelettes urinaires reçues en petite quantité",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "non", obs: "Photocopie rangée dans un classeur de bureau, non affichée et non consultée pendant l'observation." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Cahier de référence tenu par la titulaire." },
      { item: "Supports d'information destinés aux femmes", present: "partiellement", accessible: "partiellement", obs: "Une affiche décollée sur la vaccination ; rien sur l'HTA ni le diabète." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Colonne tension artérielle renseignée sur la grande majorité des lignes : la tenue du registre est ici la plus soignée des trois centres ruraux observés.",
      tracageReference: "oui — cahier de référence distinct, 3 cas orientés sur le mois, avec mention du motif",
    },
    E: "Affluence modérée. La titulaire tient un cahier de référence de sa propre initiative, hors support officiel. Une femme arrivée à un terme avancé pour un premier contact est reçue en priorité. Un agent de santé communautaire passe déposer une liste de femmes enceintes de son village.",
    F: "La tenue du registre et le cahier de référence montrent qu'une pratique de traçabilité peut exister sans support fourni : elle repose ici sur une personne, ce qui la rend fragile. À rapprocher des propos de la titulaire sur les indicateurs demandés par la supervision. Le glucomètre en panne depuis une date indéterminée interroge le circuit de maintenance, que ni le guide d'entretien ni la grille n'avaient anticipé — élément à ajouter aux notes contextuelles.",
  },
];
