// observations-vague2.mjs — Annexe 2 remplie : onze grilles d'observation.
// DONNÉES SIMULÉES. L'observation porte sur le service, jamais sur les personnes
// ni sur le contenu d'une consultation (annexe 2, § 1 et § 4.2.7 du protocole).
// Les registres ne sont consultés que sous forme agrégée, sans relevé nominatif.

const hygiene = (etat = "savon et solution hydroalcoolique présents") =>
  ({ item: "Consommables d'hygiène", present: "oui", nombre: null, etat, obs: "" });

export const observationsV2 = [
  {
    cs: "CS01", secteur: "urbain", date: "21/09/2026", heures: "07h30 – 12h20",
    A: {
      sallesCpn: 3, echangeNonEntendu: "oui",
      detail: "Deux salles de consultation individuelles fermées et une salle de constantes distincte, avec un paravent devant la table de mesure.",
      femmesRecues: 51, professionnels: 4, posteConstantes: "oui, salle distincte avec un agent affecté",
      dureeMoyenne: "environ 1 h 05",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 3, etat: "2 électroniques et 1 manuel, tous fonctionnels", obs: "Brassard grande taille présent — seul centre observé à en disposer." },
      { item: "Glucomètre", present: "oui", nombre: 2, etat: "fonctionnels, un de réserve sous clé", obs: "Utilisé à plusieurs reprises pendant la matinée." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 48, etat: "péremption 04/2027", obs: "Fiche de stock tenue à jour, seuil de réapprovisionnement inscrit." },
      { item: "Balance", present: "oui", nombre: 2, etat: "fonctionnelles", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "toise fixée au mur", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 90, etat: "péremption 06/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non — aucune rupture signalée sur la période",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiché au poste de constantes, en kinyarwanda, avec seuils et conduite à tenir." },
      { item: "Protocole diabète en grossesse", present: "oui", accessible: "oui", obs: "Algorithme affiché à côté du précédent, avec les critères de dépistage ciblé." },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Fiche de référence à deux volets ; le second volet (contre-référence) revient parfois rempli de l'hôpital — huit retours classés sur le trimestre." },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Quatre affiches illustrées en kinyarwanda, dont une sur la tension pendant la grossesse ; un dépliant à emporter, en nombre limité." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension artérielle renseignée sur la quasi-totalité des lignes. Colonne glycémie renseignée sur environ une ligne sur trois, ce qui correspond au dépistage ciblé décrit par l'équipe.",
      tracageReference: "oui — registre de référence et classeur des contre-références",
    },
    E: "Centre le mieux doté des seize observés, et le seul où le dépistage glycémique se fait sous les yeux de l'observateur. Affluence la plus forte de la série, absorbée par une organisation en trois postes. Un stagiaire est présent au poste de constantes, encadré. Une femme demande un dépliant ; il n'en reste plus en fin de matinée.",
    F: "Ce centre change la lecture de l'ensemble : il montre que le dépistage complet est réalisable dans le district, et non une exigence hors d'atteinte. Mais il le montre dans le secteur le moins pauvre et le plus proche de l'hôpital — la variable équité se lit donc dans la répartition des moyens entre centres, autant que dans les pratiques au sein d'un centre. À ne pas présenter comme un modèle transposable sans dire ce qui le rend possible.",
  },
  {
    cs: "CS04", secteur: "rural périphérique", date: "21/09/2026", heures: "08h15 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "partiellement",
      detail: "Salle fermée, mais la fenêtre donne sur l'attente et reste ouverte pour la ventilation.",
      femmesRecues: 26, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 50",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel, fonctionnel", obs: "Stéthoscope usé ; l'équipe signale une difficulté d'auscultation en ambiance bruyante." },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 15, etat: "péremption 03/2027", obs: "" },
      hygiene("savon présent, solution hydroalcoolique absente"),
    ],
    ruptureTroisMois: "oui — bandelettes urinaires, rupture d'environ deux semaines en août 2026",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "Fiche de référence du district, sans volet de retour." },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Colonne tension renseignée sur environ quatre lignes sur cinq.",
      tracageReference: "oui — souches conservées",
    },
    E: "Matinée calme. Le titulaire assure à la fois la CPN et les rapports, et s'absente vingt minutes pour une réunion téléphonique avec le district. Pendant ce temps, la seconde professionnelle poursuit seule.",
    F: "Centre « moyen » à tous égards : ni démuni, ni outillé. C'est précisément ce profil, le plus fréquent, qui manquait à la vague 1, construite sur des contrastes. Rien de marquant entre propos et constats.",
  },
  {
    cs: "CS05", secteur: "rural périphérique", date: "22/09/2026", heures: "08h40 – 12h10",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée, attente sous un auvent distant de quelques mètres.",
      femmesRecues: 19, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 30",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel", obs: "Inutilisable faute de bandelettes valides." },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 30, etat: "PÉRIMÉES depuis 05/2026", obs: "Flacons conservés dans l'armoire ; l'équipe dit attendre leur remplacement." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 35, etat: "péremption 02/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie valides absentes depuis mai 2026",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "partiellement", obs: "Rangé dans un classeur sur le bureau." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Tension renseignée régulièrement. Pas de colonne glycémie.",
      tracageReference: "oui",
    },
    E: "Affluence la plus faible des centres ruraux observés. L'équipe explique que la route d'accès devient impraticable en saison des pluies et que la fréquentation chute alors fortement. Une femme arrive à pied après, dit-elle, plus de deux heures de marche.",
    F: "Le paradoxe de ce centre — un glucomètre en état de marche et trente bandelettes inutilisables — dit quelque chose du circuit d'approvisionnement que l'inventaire « présent / absent » ne capte pas : l'intrant est là, et il ne sert pas. La grille devrait distinguer « présent » et « utilisable » ; à proposer en révision de l'annexe 2.",
  },
  {
    cs: "CS06", secteur: "urbain", date: "22/09/2026", heures: "07h45 – 12h30",
    A: {
      sallesCpn: 2, echangeNonEntendu: "partiellement",
      detail: "Deux salles, dont une sert aussi au planning familial ; les constantes sont prises dans un couloir semi-ouvert.",
      femmesRecues: 44, professionnels: 3, posteConstantes: "oui, tenu ce jour-là par un stagiaire",
      dureeMoyenne: "environ 1 h 35",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "1 électronique fonctionnel ; 1 électronique en panne", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel", obs: "" },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 5, etat: "péremption 12/2026", obs: "Stock très faible." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "toise", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 50, etat: "péremption 04/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie en quantité insuffisante, réapprovisionnement partiel",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiché, en anglais." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "partiellement", obs: "Une affiche sur la nutrition, en kinyarwanda." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Tension renseignée régulièrement ; écritures de plusieurs mains différentes sur une même semaine.",
      tracageReference: "oui",
    },
    E: "Centre situé sur l'axe routier, affluence forte. L'équipe indique que deux professionnels ont été réaffectés dans l'année ; la participante interrogée est arrivée il y a moins de deux ans. Le stagiaire au poste de constantes annonce les valeurs à voix haute.",
    F: "La multiplicité des écritures dans le registre et la présence d'un stagiaire aux constantes rendent visible un facteur que la vague 1 n'avait pas fait apparaître : la rotation du personnel. Elle dilue les consignes et interrompt la transmission des pratiques — à rapprocher du code « transmission informelle entre collègues ».",
  },
  {
    cs: "CS08", secteur: "rural périphérique", date: "23/09/2026", heures: "08h00 – 11h50",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée ; l'attente se fait dans une pièce distincte.",
      femmesRecues: 28, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 40",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 22, etat: "péremption 05/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non renseigné",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Une affiche FAITE À LA MAIN par l'équipe, en kinyarwanda, sur les signes de danger de la grossesse, dont « maux de tête forts » et « gonflement du visage ». Dessins simples, lisible pour une personne peu alphabétisée." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Tension renseignée régulièrement.",
      tracageReference: "oui",
    },
    E: "Deux agents de santé communautaire passent dans la matinée : l'un apporte la liste des femmes enceintes repérées dans son village, l'autre raccompagne une femme orientée la semaine précédente. L'équipe et les agents se connaissent par leur nom.",
    F: "L'affiche faite à la main est l'élément le plus instructif de la journée : elle montre une réponse locale à l'absence de supports fournis, et elle est plus lisible que les affiches imprimées vues ailleurs. Le lien avec les agents de santé communautaire ouvre une piste absente du cadre conceptuel : le relais communautaire comme prolongement du dépistage.",
  },
  {
    cs: "CS09", secteur: "rural périphérique", date: "23/09/2026", heures: "08h30 – 11h30",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Bâtiment récent ; salle fermée, carrelée, bien éclairée.",
      femmesRecues: 14, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 10",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique NEUF, fonctionnel", obs: "Reçu à l'ouverture du centre." },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "Prévu dans la dotation selon l'équipe, non livré." },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "neuve", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "non", nombre: 0, etat: "—", obs: "Non encore livrées." },
      hygiene(),
    ],
    ruptureTroisMois: "sans objet — dotation initiale incomplète, non une rupture",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "non", accessible: "—", obs: "Orientation écrite sur le carnet." },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "partiellement", accessible: "oui", obs: "Le registre standard n'est pas encore livré : un cahier quadrillé en tient lieu, avec des colonnes tracées à la règle." },
    ],
    D: {
      rubriqueTa: "oui (colonne tracée à la main)", rubriqueGlycemie: "non",
      renseignement: "Colonne tension présente dans le cahier et renseignée ; la tenue dépend entièrement de l'équipe, sans modèle imposé.",
      tracageReference: "non",
    },
    E: "Ancien poste de santé récemment érigé en centre de santé. Le bâtiment et l'équipement de base sont neufs ; les supports, les intrants et la dotation complète ne suivent pas encore. Faible fréquentation, que l'équipe attribue au fait que la population continue de se rendre à l'ancien centre de rattachement.",
    F: "Ce centre montre une forme d'inégalité qui n'est ni une rupture ni une panne : une dotation qui n'est pas encore arrivée. Il interroge le calendrier de mise en service plus que la gestion courante — élément non anticipé par la grille.",
  },
  {
    cs: "CS10", secteur: "rural périphérique", date: "24/09/2026", heures: "07h50 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "partiellement",
      detail: "Salle fermée, mais un passage vers la pharmacie la traverse.",
      femmesRecues: 33, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 2 h",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel", obs: "" },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 14, etat: "péremption 01/2027", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 30, etat: "péremption 03/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "Affiché." },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Tension renseignée. Une proportion notable de lignes ne comporte qu'une seule visite, sans suite.",
      tracageReference: "oui",
    },
    E: "Population décrite par l'équipe comme mobile : travailleuses agricoles saisonnières, femmes de passage venant d'autres secteurs ou d'autres districts. Plusieurs femmes présentent un carnet ouvert ailleurs. Le registre comporte de nombreuses premières visites sans visite suivante.",
    F: "La mobilité des femmes pose une question que le cadre conceptuel ne traite pas : le dépistage suppose une continuité de suivi que la trajectoire même de certaines femmes rend impossible. Les lignes sans suite du registre ne sont pas des « perdues de vue » au sens habituel : elles ont pu être suivies ailleurs. À ne pas interpréter comme un défaut du service.",
  },
  {
    cs: "CS12", secteur: "rural périphérique", date: "24/09/2026", heures: "08h00 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée, attente extérieure à distance.",
      femmesRecues: 25, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 45",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique, fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel", obs: "" },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "En rupture depuis environ deux mois selon l'équipe." },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 18, etat: "péremption 02/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "oui — bandelettes de glycémie, environ deux mois",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "" },
      { item: "Protocole diabète en grossesse", present: "oui", accessible: "partiellement", obs: "Photocopie dans un classeur." },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "oui",
      renseignement: "Tension renseignée régulièrement. Colonne glycémie renseignée jusqu'à la rupture, vide depuis.",
      tracageReference: "oui",
    },
    E: "Organisation stable, équipe ancienne. La colonne glycémie du registre montre nettement la date de la rupture : renseignée régulièrement jusqu'à fin juillet, vide ensuite.",
    F: "Le registre est ici un instrument de mesure inattendu : la date de rupture s'y lit sans qu'il soit besoin de la demander. Les registres pourraient servir, dans l'étude réelle, à documenter les ruptures plus sûrement que la mémoire des équipes — sous réserve de rester sur des données agrégées.",
  },
  {
    cs: "CS13", secteur: "rural périphérique", date: "27/09/2026", heures: "07h40 – 12h30",
    A: {
      sallesCpn: 2, echangeNonEntendu: "partiellement",
      detail: "Deux salles, portes souvent ouvertes en raison de l'affluence.",
      femmesRecues: 46, professionnels: 3, posteConstantes: "non — constantes prises en salle",
      dureeMoyenne: "environ 2 h 20",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 2, etat: "1 électronique fonctionnel ; 1 manuel fonctionnel", obs: "" },
      { item: "Glucomètre", present: "oui", nombre: 1, etat: "fonctionnel", obs: "" },
      { item: "Bandelettes de glycémie", present: "oui", nombre: 9, etat: "péremption 11/2026", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "fonctionnelle", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 40, etat: "péremption 04/2027", obs: "" },
      hygiene(),
    ],
    ruptureTroisMois: "non",
    C: [
      { item: "Protocole / algorithme HTA", present: "oui", accessible: "oui", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "oui", accessible: "oui", obs: "Une affiche sur les signes de danger." },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Colonne tension renseignée sur la TOTALITÉ des lignes consultées. Sur les pages examinées, une part très élevée des valeurs inscrites est identique (« 120/80 » ou « 110/70 »), dans une proportion supérieure à celle observée dans les autres centres.",
      tracageReference: "oui",
    },
    E: "Affluence parmi les plus fortes de la série, dans un centre rural. Trois professionnels pour quarante-six femmes. Pendant la période d'observation, plusieurs femmes sortent de la salle en moins de cinq minutes.",
    F: "La concentration de valeurs identiques dans un registre intégralement rempli ne prouve rien par elle-même et ne doit être imputée à personne : elle peut refléter des valeurs réellement fréquentes, une habitude d'arrondi, ou une inscription faite sans mesure sous la pression de l'affluence. Elle invite en revanche à ne pas lire un registre complet comme la preuve d'un dépistage réalisé. À confronter aux propos de la participante de ce centre, qui aborde elle-même le sujet.",
  },
  {
    cs: "CS15", secteur: "rural périphérique", date: "28/09/2026", heures: "08h20 – 11h45",
    A: {
      sallesCpn: 1, echangeNonEntendu: "non",
      detail: "Salle unique dont la porte ne ferme plus ; l'attente est dans le couloir attenant.",
      femmesRecues: 22, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 50",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "manuel ancien, poire réparée au ruban adhésif", obs: "Fonctionne, mais la lecture demande plusieurs tentatives." },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "mécanique, à étalonner", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 10, etat: "péremption 12/2026", obs: "" },
      hygiene("savon présent, eau au bidon"),
    ],
    ruptureTroisMois: "oui — bandelettes urinaires intermittentes",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "" },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Colonne tension renseignée sur environ deux lignes sur trois.",
      tracageReference: "oui",
    },
    E: "Équipement le plus vétuste de la série après CS11. Le tensiomètre réparé fonctionne mais allonge chaque mesure. Ambiance calme, rapports cordiaux.",
    F: "La porte qui ne ferme pas résume l'absence d'espace confidentiel mieux que toute catégorie de la grille. Rien de marquant entre propos et constats ; le participant décrit lui-même l'appareil réparé.",
  },
  {
    cs: "CS16", secteur: "rural périphérique", date: "29/09/2026", heures: "08h30 – 12h00",
    A: {
      sallesCpn: 1, echangeNonEntendu: "oui",
      detail: "Salle fermée ; électricité fournie par un panneau solaire, éclairage limité par temps couvert.",
      femmesRecues: 21, professionnels: 2, posteConstantes: "non",
      dureeMoyenne: "environ 1 h 40",
    },
    B: [
      { item: "Tensiomètre", present: "oui", nombre: 1, etat: "électronique sur piles, fonctionnel ce jour-là", obs: "L'équipe indique que les piles manquent régulièrement et qu'elle en achète parfois elle-même." },
      { item: "Glucomètre", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Bandelettes de glycémie", present: "non", nombre: 0, etat: "—", obs: "" },
      { item: "Balance", present: "oui", nombre: 1, etat: "mécanique", obs: "" },
      { item: "Toise / mètre ruban", present: "oui", nombre: 1, etat: "mètre ruban", obs: "" },
      { item: "Bandelettes urinaires", present: "oui", nombre: 12, etat: "péremption 01/2027", obs: "" },
      hygiene("savon présent"),
    ],
    ruptureTroisMois: "oui — piles du tensiomètre, de façon répétée",
    C: [
      { item: "Protocole / algorithme HTA", present: "non", accessible: "—", obs: "" },
      { item: "Protocole diabète en grossesse", present: "non", accessible: "—", obs: "" },
      { item: "Fiche ou circuit de référence formalisé", present: "oui", accessible: "oui", obs: "" },
      { item: "Supports d'information destinés aux femmes", present: "non", accessible: "—", obs: "" },
      { item: "Registre de consultation prénatale", present: "oui", accessible: "oui", obs: "Complété par un CAHIER DE SUIVI APRÈS L'ACCOUCHEMENT, créé par la titulaire, où sont notées les femmes dépistées avec une tension élevée pendant la grossesse." },
    ],
    D: {
      rubriqueTa: "oui", rubriqueGlycemie: "non",
      renseignement: "Tension renseignée régulièrement.",
      tracageReference: "oui — et suivi après l'accouchement tracé dans le cahier dédié",
    },
    E: "Centre le plus éloigné du district. Un agent de santé communautaire vient signaler une femme enceinte qui n'est pas revenue ; la titulaire lui demande de lui rappeler son rendez-vous. Le cahier de suivi après l'accouchement compte une douzaine de noms — consulté par l'observateur sans relevé nominatif.",
    F: "Le cahier de suivi après l'accouchement répond exactement à la « discontinuité après l'accouchement » que plusieurs participants de la vague 1 avaient soulevée sans qu'aucun ne décrive de réponse. Il est l'œuvre d'une personne : fragile, non prévu par le système, et pourtant le seul dispositif de ce type observé dans le district.",
  },
];
